In [1]:
# Supress Warnings

import warnings
warnings.filterwarnings('ignore')

In [2]:
# Import the numpy and pandas packages

import numpy as np
import pandas as pd

## Task 1: Reading and Inspection

-  ### Subtask 1.1: Import and read

Import and read the movie database. Store it in a variable called `movies`.

In [3]:
# Reading the given csv file as a dataframe named movies
movies = pd.read_csv("Movie+Assignment+Data.csv")

-  ### Subtask 1.2: Inspect the dataframe

Inspect the dataframe's columns, shapes, variable types etc.

In [4]:
# Write your code for inspection here
print(movies.shape)
print(list(movies.columns))
movies.info()
movies.describe()

(5043, 28)
['color', 'director_name', 'num_critic_for_reviews', 'duration', 'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name', 'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name', 'movie_title', 'num_voted_users', 'cast_total_facebook_likes', 'actor_3_name', 'facenumber_in_poster', 'plot_keywords', 'movie_imdb_link', 'num_user_for_reviews', 'language', 'country', 'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes', 'imdb_score', 'aspect_ratio', 'movie_facebook_likes']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
color                        5024 non-null object
director_name                4939 non-null object
num_critic_for_reviews       4993 non-null float64
duration                     5028 non-null float64
director_facebook_likes      4939 non-null float64
actor_3_facebook_likes       5020 non-null float64
actor_2_name                 5030 non-null object
actor_1_facebook_likes       5036 non-null float64
gross                        4159 non-null float64
genres                       5043 non-null object
actor_1_name                 5036 non-null object
movie_title                  5043 non-null object
num_voted_users              5043 non-null int64
cast_total_facebook_likes    5043 non-null int64
actor_3_name                 5020 non-null object
facenumber_in_poster         5030 non-null float64
plot_keywords                4890 non-null object
movie_imdb_link              5043 non-null object
num_user_for_reviews         5022 non-null float64
language                     5031 non-null object
country                      5038 non-null object
content_rating               4740 non-null object
budget                       4551 non-null float64
title_year                   4935 non-null float64
actor_2_facebook_likes       5030 non-null float64
imdb_score                   5043 non-null float64
aspect_ratio                 4714 non-null float64
movie_facebook_likes         5043 non-null int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
count,4993.000000,5028.000000,4939.000000,5020.000000,5036.000000,4.159000e+03,5.043000e+03,5043.000000,5030.000000,5022.000000,4.551000e+03,4935.000000,5030.000000,5043.000000,4714.000000,5043.000000
mean,140.194272,107.201074,686.509212,645.009761,6560.047061,4.846841e+07,8.366816e+04,9699.063851,1.371173,272.770808,3.975262e+07,2002.470517,1651.754473,6.442138,2.220403,7525.964505
std,121.601675,25.197441,2813.328607,1665.041728,15020.759120,6.845299e+07,1.384853e+05,18163.799124,2.013576,377.982886,2.061149e+08,12.474599,4042.438863,1.125116,1.385113,19320.445110
min,1.000000,7.000000,0.000000,0.000000,0.000000,1.620000e+02,5.000000e+00,0.000000,0.000000,1.000000,2.180000e+02,1916.000000,0.000000,1.600000,1.180000,0.000000
25%,50.000000,93.000000,7.000000,133.000000,614.000000,5.340988e+06,8.593500e+03,1411.000000,0.000000,65.000000,6.000000e+06,1999.000000,281.000000,5.800000,1.850000,0.000000
50%,110.000000,103.000000,49.000000,371.500000,988.000000,2.551750e+07,3.435900e+04,3090.000000,1.000000,156.000000,2.000000e+07,2005.000000,595.000000,6.600000,2.350000,166.000000
75%,195.000000,118.000000,194.500000,636.000000,11000.000000,6.230944e+07,9.630900e+04,13756.500000,2.000000,326.000000,4.500000e+07,2011.000000,918.000000,7.200000,2.350000,3000.000000
max,813.000000,511.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1.689764e+06,656730.000000,43.000000,5060.000000,1.221550e+10,2016.000000,137000.000000,9.500000,16.000000,349000.000000

## Task 2: Cleaning the Data

-  ### Subtask 2.1: Inspect Null values

Find out the number of Null values in all the columns and rows. Also, find the percentage of Null values in each column. Round off the percentages upto two decimal places.

In [5]:
# Write your code for column-wise null count here
movies.isnull().sum()

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      12
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [6]:
# Write your code for row-wise null count here
movies.isnull().sum(axis=1)

0        0
1        0
2        0
3        0
4       14
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
5013     2
5014     2
5015     0
5016     5
5017     2
5018     2
5019     2
5020     5
5021     1
5022     4
5023     2
5024     1
5025     0
5026     0
5027     0
5028     3
5029     1
5030     5
5031     3
5032     4
5033     0
5034     1
5035     0
5036     3
5037     1
5038     4
5039     5
5040     4
5041     2
5042     0
Length: 5043, dtype: int64

In [7]:
# Write your code for column-wise null percentages here
round(100*(movies.isnull().sum()/len(movies.index)), 2)

color                         0.38
director_name                 2.06
num_critic_for_reviews        0.99
duration                      0.30
director_facebook_likes       2.06
actor_3_facebook_likes        0.46
actor_2_name                  0.26
actor_1_facebook_likes        0.14
gross                        17.53
genres                        0.00
actor_1_name                  0.14
movie_title                   0.00
num_voted_users               0.00
cast_total_facebook_likes     0.00
actor_3_name                  0.46
facenumber_in_poster          0.26
plot_keywords                 3.03
movie_imdb_link               0.00
num_user_for_reviews          0.42
language                      0.24
country                       0.10
content_rating                6.01
budget                        9.76
title_year                    2.14
actor_2_facebook_likes        0.26
imdb_score                    0.00
aspect_ratio                  6.52
movie_facebook_likes          0.00
dtype: float64

-  ### Subtask 2.2: Drop unecessary columns

For this assignment, you will mostly be analyzing the movies with respect to the ratings, gross collection, popularity of movies, etc. So many of the columns in this dataframe are not required. So it is advised to drop the following columns.
-  color
-  director_facebook_likes
-  actor_1_facebook_likes
-  actor_2_facebook_likes
-  actor_3_facebook_likes
-  actor_2_name
-  cast_total_facebook_likes
-  actor_3_name
-  duration
-  facenumber_in_poster
-  content_rating
-  country
-  movie_imdb_link
-  aspect_ratio
-  plot_keywords

In [8]:
# Write your code for dropping the columns here. It is advised to keep inspecting the dataframe after each set of operations 
movies = movies.drop('color', axis=1)
movies = movies.drop('director_facebook_likes', axis=1)
movies = movies.drop('actor_1_facebook_likes', axis=1)
movies = movies.drop('actor_2_facebook_likes', axis=1)
movies = movies.drop('actor_3_facebook_likes', axis=1)
movies = movies.drop('actor_2_name', axis=1)
movies = movies.drop('cast_total_facebook_likes', axis=1)
movies = movies.drop('actor_3_name', axis=1)
movies = movies.drop('duration', axis=1)
movies = movies.drop('facenumber_in_poster', axis=1)
movies = movies.drop('content_rating', axis=1)
movies = movies.drop('country', axis=1)
movies = movies.drop('movie_imdb_link', axis=1)
movies = movies.drop('aspect_ratio', axis=1)
movies = movies.drop('plot_keywords', axis=1)

print(movies.shape)
print(list(movies.columns))
print(100*(movies.isnull().sum()/len(movies.index)))

(5043, 13)
['director_name', 'num_critic_for_reviews', 'gross', 'genres', 'actor_1_name', 'movie_title', 'num_voted_users', 'num_user_for_reviews', 'language', 'budget', 'title_year', 'imdb_score', 'movie_facebook_likes']
director_name              2.062265
num_critic_for_reviews     0.991473
gross                     17.529248
genres                     0.000000
actor_1_name               0.138806
movie_title                0.000000
num_voted_users            0.000000
num_user_for_reviews       0.416419
language                   0.237954
budget                     9.756098
title_year                 2.141582
imdb_score                 0.000000
movie_facebook_likes       0.000000
dtype: float64

-  ### Subtask 2.3: Drop unecessary rows using columns with high Null percentages

Now, on inspection you might notice that some columns have large percentage (greater than 5%) of Null values. Drop all the rows which have Null values for such columns.

In [10]:
# Write your code for dropping the rows here
100*(movies.isnull().sum()/len(movies.index)) > 5 #This is to find out the columns with more than 5% of values as null
movies = movies[~movies.gross.isnull()]          # Two ways of doing it.
movies = movies[~np.isnan(movies['budget'])]
print(movies.shape)
print(list(movies.columns))

(3891, 13)
['director_name', 'num_critic_for_reviews', 'gross', 'genres', 'actor_1_name', 'movie_title', 'num_voted_users', 'num_user_for_reviews', 'language', 'budget', 'title_year', 'imdb_score', 'movie_facebook_likes']

In [11]:
# Checking the column-wise null percentages again for inspection
round(100*(movies.isnull().sum()/len(movies.index)),2)

director_name             0.00
num_critic_for_reviews    0.03
gross                     0.00
genres                    0.00
actor_1_name              0.08
movie_title               0.00
num_voted_users           0.00
num_user_for_reviews      0.00
language                  0.08
budget                    0.00
title_year                0.00
imdb_score                0.00
movie_facebook_likes      0.00
dtype: float64

-  ### Subtask 2.4: Drop unecessary rows

Some of the rows might have greater than five NaN values. Such rows aren't of much use for the analysis and hence, should be removed.

In [12]:
# Write your code for dropping the rows here
movies = movies[movies.isnull().sum(axis=1) <= 5]
print(movies.shape)
print(list(movies.columns))

(3891, 13)
['director_name', 'num_critic_for_reviews', 'gross', 'genres', 'actor_1_name', 'movie_title', 'num_voted_users', 'num_user_for_reviews', 'language', 'budget', 'title_year', 'imdb_score', 'movie_facebook_likes']

-  ### Subtask 2.5: Fill NaN values

You might notice that the `language` column has some NaN values. Here, on inspection, you will see that it is safe to replace all the missing values with `'English'`.

In [13]:
# Write your code for filling the NaN values in the 'language' column here
movies.fillna(value={'language':'English'},inplace=True)

In [14]:
# Checking whether previous operation was successful - NaN values in language columns replaced by 'English'
movies[movies.language.isnull()] # This should return 0 rows

Empty DataFrame
Columns: [director_name, num_critic_for_reviews, gross, genres, actor_1_name, movie_title, num_voted_users, num_user_for_reviews, language, budget, title_year, imdb_score, movie_facebook_likes]
Index: []

-  ### Subtask 2.6: Check the number of retained rows

You might notice that two of the columns viz. `num_critic_for_reviews` and `actor_1_name` have small percentages of NaN values left. You can let these columns as it is for now. Check the number and percentage of the rows retained after completing all the tasks above.

In [15]:
# Write your code for checking number of retained rows here
print(len(movies.index))
print(round(len(movies.index)*100/5043,2))

3891
77.16

**Checkpoint 1:** You might have noticed that we still have around `77%` of the rows!

## Task 3: Data Analysis

-  ### Subtask 3.1: Change the unit of columns

Convert the unit of the `budget` and `gross` columns from `$` to `million $`.

In [16]:
# Write your code for unit conversion here

def convert_to_millions(x):
    return round(x/1000000,2)

movies['gross'] = movies['gross'].apply(convert_to_millions)
movies['budget'] = movies['budget'].apply(convert_to_millions)
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760.51,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.00,2009.0,7.9,33000
1,Gore Verbinski,302.0,309.40,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300.00,2007.0,7.1,0
2,Sam Mendes,602.0,200.07,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245.00,2015.0,6.8,85000
3,Christopher Nolan,813.0,448.13,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250.00,2012.0,8.5,164000
5,Andrew Stanton,462.0,73.06,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263.70,2012.0,6.6,24000
6,Sam Raimi,392.0,336.53,Action|Adventure|Romance,J.K. Simmons,Spider-Man 3,383056,1902.0,English,258.00,2007.0,6.2,0
7,Nathan Greno,324.0,200.81,Adventure|Animation|Comedy|Family|Fantasy|Musi...,Brad Garrett,Tangled,294810,387.0,English,260.00,2010.0,7.8,29000
8,Joss Whedon,635.0,458.99,Action|Adventure|Sci-Fi,Chris Hemsworth,Avengers: Age of Ultron,462669,1117.0,English,250.00,2015.0,7.5,118000
9,David Yates,375.0,301.96,Adventure|Family|Fantasy|Mystery,Alan Rickman,Harry Potter and the Half-Blood Prince,321795,973.0,English,250.00,2009.0,7.5,10000
10,Zack Snyder,673.0,330.25,Action|Adventure|Sci-Fi,Henry Cavill,Batman v Superman: Dawn of Justice,371639,3018.0,English,250.00,2016.0,6.9,197000
11,Bryan Singer,434.0,200.07,Action|Adventure|Sci-Fi,Kevin Spacey,Superman Returns,240396,2367.0,English,209.00,2006.0,6.1,0
12,Marc Forster,403.0,168.37,Action|Adventure,Giancarlo Giannini,Quantum of Solace,330784,1243.0,English,200.00,2008.0,6.7,0
13,Gore Verbinski,313.0,423.03,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: Dead Man's Chest,522040,1832.0,English,225.00,2006.0,7.3,5000
14,Gore Verbinski,450.0,89.29,Action|Adventure|Western,Johnny Depp,The Lone Ranger,181792,711.0,English,215.00,2013.0,6.5,48000
15,Zack Snyder,733.0,291.02,Action|Adventure|Fantasy|Sci-Fi,Henry Cavill,Man of Steel,548573,2536.0,English,225.00,2013.0,7.2,118000
16,Andrew Adamson,258.0,141.61,Action|Adventure|Family|Fantasy,Peter Dinklage,The Chronicles of Narnia: Prince Caspian,149922,438.0,English,225.00,2008.0,6.6,0
17,Joss Whedon,703.0,623.28,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.00,2012.0,8.1,123000
18,Rob Marshall,448.0,241.06,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: On Stranger Tides,370704,484.0,English,250.00,2011.0,6.7,58000
19,Barry Sonnenfeld,451.0,179.02,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,Will Smith,Men in Black 3,268154,341.0,English,225.00,2012.0,6.8,40000
20,Peter Jackson,422.0,255.11,Adventure|Fantasy,Aidan Turner,The Hobbit: The Battle of the Five Armies,354228,802.0,English,250.00,2014.0,7.5,65000
21,Marc Webb,599.0,262.03,Action|Adventure|Fantasy,Emma Stone,The Amazing Spider-Man,451803,1225.0,English,230.00,2012.0,7.0,56000
22,Ridley Scott,343.0,105.22,Action|Adventure|Drama|History,Mark Addy,Robin Hood,211765,546.0,English,200.00,2010.0,6.7,17000
23,Peter Jackson,509.0,258.36,Adventure|Fantasy,Aidan Turner,The Hobbit: The Desolation of Smaug,483540,951.0,English,225.00,2013.0,7.9,83000
24,Chris Weitz,251.0,70.08,Adventure|Family|Fantasy,Christopher Lee,The Golden Compass,149019,666.0,English,180.00,2007.0,6.1,0
25,Peter Jackson,446.0,218.05,Action|Adventure|Drama|Romance,Naomi Watts,King Kong,316018,2618.0,English,207.00,2005.0,7.2,0
26,James Cameron,315.0,658.67,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.00,1997.0,7.7,26000
27,Anthony Russo,516.0,407.20,Action|Adventure|Sci-Fi,Robert Downey Jr.,Captain America: Civil War,272670,1022.0,English,250.00,2016.0,8.2,72000
28,Peter Berg,377.0,65.17,Action|Adventure|Sci-Fi|Thriller,Liam Neeson,Battleship,202382,751.0,English,209.00,2012.0,5.9,44000
29,Colin Trevorrow,644.0,652.18,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.00,2015.0,7.0,150000
30,Sam Mendes,750.0,304.36,Action|Adventure|Thriller,Albert Finney,Skyfall,522030,1498.0,English,200.00,2012.0,7.8,80000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4959,Robert Townsend,21.0,5.23,Comedy,Robert Townsend,Hollywood Shuffle,2770,32.0,English,0.10,1987.0,7.0,471
4962,Larry Blamire,88.0,0.11,Comedy|Horror|Sci-Fi,Fay Masterson,The Lost Skeleton of Cadavra,4117,118.0,English,0.04,2001.0,7.0,0
4964,E.L. Katz,193.0,0.06,Comedy|Crime|Drama|Horror|Thriller,Brighton Sharbino,Cheap Thrills,12796,52.0,English,0.20,2013.0,6.8,0
4971,Dennis Iliadis,241.0,32.72,Crime|Horror|Thriller,Tony Goldwyn,The Last House on the Left,67824,279.0,English,15.00,2009.0,6.6,0
4973,Darren Aronofsky,138.0,3.22,Drama|Mystery|Thriller,Mark Margolis,Pi,142619,586.0,English,0.06,1998.0,7.5,24000
4975,Myles Berkowitz,32.0,0.54,Biography|Comedy|Romance,Tia Carrere,20 Dates,1622,83.0,English,0.06,1998.0,5.3,30
4977,Morgan Spurlock,193.0,11.53,Comedy|Documentary|Drama,Chemeeka Walker,Super Size Me,85028,404.0,English,0.07,2004.0,7.3,0
4978,Brandon Trost,66.0,0.04,Comedy,Clifton Collins Jr.,The FP,1389,22.0,English,0.06,2011.0,5.6,0
4979,Joe Swanberg,65.0,0.03,Comedy|Drama,Anna Kendrick,Happy Christmas,5507,23.0,English,0.07,2014.0,5.6,812
4984,Edward Burns,36.0,10.25,Comedy|Drama|Romance,Shari Albert,The Brothers McMullen,6375,36.0,English,0.03,1995.0,6.6,265
4987,Lena Dunham,113.0,0.39,Comedy|Drama|Romance,Lena Dunham,Tiny Furniture,11816,35.0,English,0.07,2010.0,6.3,0
4997,David Gordon Green,75.0,0.24,Drama,Paul Schneider,George Washington,6246,76.0,English,0.04,2000.0,7.5,451
4998,Kevin Jordan,21.0,0.28,Comedy|Romance,Derick Martini,Smiling Fish & Goat on Fire,2631,26.0,English,0.04,1999.0,7.6,0
5004,Mike Bruce,3.0,0.24,Western,Joseph Campanella,The Legend of God's Gun,143,9.0,English,0.03,2007.0,4.1,13
5008,Kevin Smith,136.0,3.15,Comedy,Jason Mewes,Clerks,181749,615.0,English,0.23,1994.0,7.8,0
5009,James Bidgood,8.0,0.01,Drama|Fantasy,Don Brooks,Pink Narcissus,803,16.0,English,0.03,1971.0,6.7,85
5011,Neil LaBute,80.0,2.86,Comedy|Drama,Stacy Edwards,In the Company of Men,11550,197.0,English,0.03,1997.0,7.3,489
5012,David Ayer,233.0,10.50,Action|Crime|Drama|Thriller,Mireille Enos,Sabotage,47502,212.0,English,35.00,2014.0,5.7,10000
5015,Richard Linklater,61.0,1.23,Comedy|Drama,Tommy Pallotta,Slacker,15103,80.0,English,0.02,1991.0,7.1,2000
5021,Jay Duplass,51.0,0.19,Comedy|Drama|Romance,Mark Duplass,The Puffy Chair,4067,71.0,English,0.01,2005.0,6.6,297
5023,Daryl Wein,22.0,0.08,Romance,Zoe Lister-Jones,Breaking Upwards,1194,8.0,English,0.01,2009.0,6.2,324
5025,John Waters,73.0,0.18,Comedy|Crime|Horror,Divine,Pink Flamingos,16792,183.0,English,0.01,1972.0,6.1,0
5026,Olivier Assayas,81.0,0.14,Drama|Music|Romance,Maggie Cheung,Clean,3924,39.0,French,0.00,2004.0,6.9,171
5027,Jafar Panahi,64.0,0.67,Drama,Fereshteh Sadre Orafaiy,The Circle,4555,26.0,Persian,0.01,2000.0,7.5,697
5029,Kiyoshi Kurosawa,78.0,0.09,Crime|Horror|Mystery|Thriller,Kôji Yakusho,The Cure,6318,50.0,Japanese,1.00,1997.0,7.4,817
5033,Shane Carruth,143.0,0.42,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371.0,English,0.01,2004.0,7.0,19000
5034,Neill Dela Llana,35.0,0.07,Thriller,Ian Gamazon,Cavite,589,35.0,English,0.01,2005.0,6.3,74
5035,Robert Rodriguez,56.0,2.04,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130.0,Spanish,0.01,1992.0,6.9,0
5037,Edward Burns,14.0,0.00,Comedy|Drama,Kerry Bishé,Newlyweds,1338,14.0,English,0.01,2011.0,6.4,413
5042,Jon Gunn,43.0,0.09,Documentary,John August,My Date with Drew,4285,84.0,English,0.00,2004.0,6.6,456

-  ### Subtask 3.2: Find the movies with highest profit

    1. Create a new column called `profit` which contains the difference of the two columns: `gross` and `budget`.
    2. Sort the dataframe using the `profit` column as reference.
    3. Extract the top ten profiting movies in descending order and store them in a new dataframe - `top10`

In [17]:
# Write your code for creating the profit column here
movies['profit'] = movies['gross']-movies['budget']

In [18]:
# Write your code for sorting the dataframe here
movies.sort_values(by='profit',ascending = False, inplace=True)

In [19]:
# Write your code to get the top 10 profiting movies here
top10 = movies.head(10)
top10

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.51,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.51
29,Colin Trevorrow,644.0,652.18,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0,2015.0,7.0,150000,502.18
26,James Cameron,315.0,658.67,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.67
3024,George Lucas,282.0,460.94,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.0,1977.0,8.7,33000,449.94
3080,Steven Spielberg,215.0,434.95,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.5,1982.0,7.9,34000,424.45
794,Joss Whedon,703.0,623.28,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.28
17,Joss Whedon,703.0,623.28,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.28
509,Roger Allers,186.0,422.78,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.0,1994.0,8.5,17000,377.78
240,George Lucas,320.0,474.54,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115.0,1999.0,6.5,13000,359.54
66,Christopher Nolan,645.0,533.32,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.0,2008.0,9.0,37000,348.32

-  ### Subtask 3.3: Drop duplicate values

After you found out the top 10 profiting movies, you might have notice a duplicate value. So, it seems like the dataframe has duplicate values as well. Drop the duplicate values from the dataframe and repeat `Subtask 3.2`.

In [20]:
# Write your code for dropping duplicate values here
movies.drop_duplicates(inplace=True)

In [21]:
# Write code for repeating subtask 2 here
top10 = movies.head(10)
top10

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.51,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.51
29,Colin Trevorrow,644.0,652.18,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0,2015.0,7.0,150000,502.18
26,James Cameron,315.0,658.67,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.67
3024,George Lucas,282.0,460.94,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.0,1977.0,8.7,33000,449.94
3080,Steven Spielberg,215.0,434.95,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.5,1982.0,7.9,34000,424.45
794,Joss Whedon,703.0,623.28,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.28
509,Roger Allers,186.0,422.78,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.0,1994.0,8.5,17000,377.78
240,George Lucas,320.0,474.54,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115.0,1999.0,6.5,13000,359.54
66,Christopher Nolan,645.0,533.32,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.0,2008.0,9.0,37000,348.32
439,Gary Ross,673.0,408.00,Adventure|Drama|Sci-Fi|Thriller,Jennifer Lawrence,The Hunger Games,701607,1959.0,English,78.0,2012.0,7.3,140000,330.00

**Checkpoint 2:** You might spot two movies directed by `James Cameron` in the list.

In [22]:
# Verification for Checkpoint 2
print(len(top10[top10['director_name']=='James Cameron'].index))

2

-  ### Subtask 3.4: Find IMDb Top 250

    1. Create a new dataframe `IMDb_Top_250` and store the top 250 movies with the highest IMDb Rating (corresponding to the column: `imdb_score`). Also make sure that for all of these movies, the `num_voted_users` is greater than 25,000.
Also add a `Rank` column containing the values 1 to 250 indicating the ranks of the corresponding films.
    2. Extract all the movies in the `IMDb_Top_250` dataframe which are not in the English language and store them in a new dataframe named `Top_Foreign_Lang_Film`.

In [23]:
# Write your code for extracting the top 250 movies as per the IMDb score here. Make sure that you store it in a new dataframe 
# and name that dataframe as 'IMDb_Top_250'
IMDb_Top_250 = movies[movies['num_voted_users'] > 25000].sort_values(by='imdb_score',ascending=False).head(250)
IMDb_Top_250.reset_index(inplace=True,drop=True)
IMDb_Top_250['rank'] = pd.Series(IMDb_Top_250.index+1)
IMDb_Top_250

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,rank
0,Frank Darabont,199.0,28.34,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144.0,English,25.00,1994.0,9.3,108000,3.34,1
1,Francis Ford Coppola,208.0,134.82,Crime|Drama,Al Pacino,The Godfather,1155770,2238.0,English,6.00,1972.0,9.2,43000,128.82,2
2,Francis Ford Coppola,149.0,57.30,Crime|Drama,Robert De Niro,The Godfather: Part II,790926,650.0,English,13.00,1974.0,9.0,14000,44.30,3
3,Christopher Nolan,645.0,533.32,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.00,2008.0,9.0,37000,348.32,4
4,Peter Jackson,328.0,377.02,Action|Adventure|Drama|Fantasy,Orlando Bloom,The Lord of the Rings: The Return of the King,1215718,3189.0,English,94.00,2003.0,8.9,16000,283.02,5
5,Steven Spielberg,174.0,96.07,Biography|Drama|History,Liam Neeson,Schindler's List,865020,1273.0,English,22.00,1993.0,8.9,41000,74.07,6
6,Sergio Leone,181.0,6.10,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780.0,Italian,1.20,1966.0,8.9,20000,4.90,7
7,Quentin Tarantino,215.0,107.93,Crime|Drama,Bruce Willis,Pulp Fiction,1324680,2195.0,English,8.00,1994.0,8.9,45000,99.93,8
8,Christopher Nolan,642.0,292.57,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200,2803.0,English,160.00,2010.0,8.8,175000,132.57,9
9,David Fincher,315.0,37.02,Drama,Brad Pitt,Fight Club,1347461,2968.0,English,63.00,1999.0,8.8,48000,-25.98,10
10,Irvin Kershner,223.0,290.16,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode V - The Empire Strikes Back,837759,900.0,English,18.00,1980.0,8.8,17000,272.16,11
11,Robert Zemeckis,149.0,329.69,Comedy|Drama,Tom Hanks,Forrest Gump,1251222,1398.0,English,55.00,1994.0,8.8,59000,274.69,12
12,Peter Jackson,297.0,313.84,Action|Adventure|Drama|Fantasy,Christopher Lee,The Lord of the Rings: The Fellowship of the R...,1238746,5060.0,English,93.00,2001.0,8.8,21000,220.84,13
13,Milos Forman,149.0,112.00,Drama,Scatman Crothers,One Flew Over the Cuckoo's Nest,680041,760.0,English,4.40,1975.0,8.7,32000,107.60,14
14,Fernando Meirelles,214.0,7.56,Crime|Drama,Alice Braga,City of God,533200,749.0,Portuguese,3.30,2002.0,8.7,28000,4.26,15
15,George Lucas,282.0,460.94,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.00,1977.0,8.7,33000,449.94,16
16,Akira Kurosawa,153.0,0.27,Action|Adventure|Drama,Takashi Shimura,Seven Samurai,229012,596.0,Japanese,2.00,1954.0,8.7,11000,-1.73,17
17,Peter Jackson,294.0,340.48,Action|Adventure|Drama|Fantasy,Christopher Lee,The Lord of the Rings: The Two Towers,1100446,2417.0,English,94.00,2002.0,8.7,10000,246.48,18
18,Martin Scorsese,192.0,46.84,Biography|Crime|Drama,Robert De Niro,Goodfellas,728685,989.0,English,25.00,1990.0,8.7,25000,21.84,19
19,Lana Wachowski,313.0,171.38,Action|Sci-Fi,Keanu Reeves,The Matrix,1217752,3646.0,English,63.00,1999.0,8.7,25000,108.38,20
20,Jonathan Demme,185.0,130.73,Crime|Drama|Horror|Thriller,Anthony Hopkins,The Silence of the Lambs,887467,916.0,English,19.00,1991.0,8.6,40000,111.73,21
21,Charles Chaplin,120.0,0.16,Comedy|Drama|Family,Paulette Goddard,Modern Times,143086,211.0,English,1.50,1936.0,8.6,0,-1.34,22
22,Tony Kaye,162.0,6.71,Crime|Drama,Ethan Suplee,American History X,782437,1420.0,English,7.50,1998.0,8.6,35000,-0.79,23
23,Steven Spielberg,219.0,216.12,Action|Drama|War,Tom Hanks,Saving Private Ryan,881236,2277.0,English,70.00,1998.0,8.6,22000,146.12,24
24,Bryan Singer,162.0,23.27,Crime|Drama|Mystery|Thriller,Kevin Spacey,The Usual Suspects,740918,1182.0,English,6.00,1995.0,8.6,28000,17.27,25
25,Hayao Miyazaki,246.0,10.05,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Spirited Away,417971,902.0,Japanese,19.00,2001.0,8.6,28000,-8.95,26
26,David Fincher,216.0,100.13,Crime|Drama|Mystery|Thriller,Morgan Freeman,Se7en,1023511,1080.0,English,33.00,1995.0,8.6,39000,67.13,27
27,Christopher Nolan,712.0,187.99,Adventure|Drama|Sci-Fi,Matthew McConaughey,Interstellar,928227,2725.0,English,165.00,2014.0,8.6,349000,22.99,28
28,Ridley Scott,265.0,187.67,Action|Drama|Romance,Djimon Hounsou,Gladiator,982637,2368.0,English,103.00,2000.0,8.5,21000,84.67,29
29,Francis Ford Coppola,261.0,78.80,Drama|War,Harrison Ford,Apocalypse Now,450676,983.0,English,31.50,1979.0,8.5,19000,47.30,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,John Lasseter,191.0,245.82,Adventure|Animation|Comedy|Family|Fantasy,Tom Hanks,Toy Story 2,385871,515.0,English,90.00,1999.0,7.9,0,155.82,221
221,John Landis,125.0,54.20,Action|Comedy|Crime|Music,John Belushi,The Blues Brothers,142448,319.0,English,27.00,1980.0,7.9,14000,27.20,222
222,James Ivory,58.0,22.95,Drama|Romance,Anthony Hopkins,The Remains of the Day,45703,156.0,English,11.50,1993.0,7.9,0,11.45,223
223,Edward Zwick,60.0,26.83,Drama|History|War,Denzel Washington,Glory,101888,365.0,English,18.00,1989.0,7.9,0,8.83,224
224,James Mangold,291.0,119.52,Biography|Drama|Music|Romance,Sandra Ellis Lafferty,Walk the Line,188637,815.0,English,28.00,2005.0,7.9,11000,91.52,225
225,Edward Zwick,60.0,26.83,Drama|History|War,Denzel Washington,Glory,101889,365.0,English,18.00,1989.0,7.9,0,8.83,226
226,Yash Chopra,29.0,2.92,Drama|Musical|Romance,Shah Rukh Khan,Veer-Zaara,34449,119.0,Hindi,7.00,2004.0,7.9,2000,-4.08,227
227,Jon Favreau,486.0,318.30,Action|Adventure|Sci-Fi,Robert Downey Jr.,Iron Man,696338,1055.0,English,140.00,2008.0,7.9,10000,178.30,228
228,James Cameron,723.0,760.51,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.00,2009.0,7.9,33000,523.51,229
229,Paul Haggis,287.0,54.56,Crime|Drama|Thriller,Don Cheadle,Crash,361169,1624.0,English,6.50,2004.0,7.9,18000,48.06,230
230,Andrew Adamson,212.0,267.65,Adventure|Animation|Comedy|Family|Fantasy,Kathleen Freeman,Shrek,467113,945.0,English,60.00,2001.0,7.9,0,207.65,231
231,Dean DeBlois,292.0,177.00,Action|Adventure|Animation|Comedy|Family|Fantasy,Gerard Butler,How to Train Your Dragon 2,221128,343.0,English,145.00,2014.0,7.9,46000,32.00,232
232,Steven Spielberg,215.0,434.95,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.50,1982.0,7.9,34000,424.45,233
233,Tim Burton,148.0,5.89,Biography|Comedy|Drama,Johnny Depp,Ed Wood,142416,420.0,English,18.00,1994.0,7.9,0,-12.11,234
234,Duncan Jones,415.0,5.01,Drama|Mystery|Sci-Fi,Kevin Spacey,Moon,260607,485.0,English,5.00,2009.0,7.9,47000,0.01,235
235,Pierre Morel,309.0,145.00,Action|Thriller,Liam Neeson,Taken,483756,974.0,English,25.00,2008.0,7.9,29000,120.00,236
236,Peter Jackson,645.0,303.00,Adventure|Fantasy,Aidan Turner,The Hobbit: An Unexpected Journey,637246,1367.0,English,180.00,2012.0,7.9,166000,123.00,237
237,Fabián Bielinsky,94.0,1.22,Crime|Drama|Thriller,Ricardo Darín,Nine Queens,38215,125.0,Spanish,1.50,2000.0,7.9,0,-0.28,238
238,Peter Jackson,509.0,258.36,Adventure|Fantasy,Aidan Turner,The Hobbit: The Desolation of Smaug,483540,951.0,English,225.00,2013.0,7.9,83000,33.36,239
239,Tim Burton,111.0,56.36,Fantasy|Romance,Johnny Depp,Edward Scissorhands,357581,588.0,English,20.00,1990.0,7.9,16000,36.36,240
240,Christophe Barratier,112.0,3.63,Drama|Music,Jean-Baptiste Maunier,The Chorus,44151,110.0,French,5.50,2004.0,7.9,0,-1.87,241
241,Yimou Zhang,283.0,0.08,Action|Adventure|History,Jet Li,Hero,149414,841.0,Mandarin,31.00,2002.0,7.9,0,-30.92,242
242,F. Gary Gray,349.0,161.03,Biography|Crime|Drama|History|Music,Aldis Hodge,Straight Outta Compton,119928,331.0,English,28.00,2015.0,7.9,76000,133.03,243
243,Darren Aronofsky,391.0,26.24,Drama|Sport,Mark Margolis,The Wrestler,251349,547.0,English,6.00,2008.0,7.9,10000,20.24,244
244,Edgar Wright,285.0,23.62,Action|Comedy|Mystery,Bill Bailey,Hot Fuzz,352695,687.0,English,8.00,2007.0,7.9,17000,15.62,245
245,Cristian Mungiu,233.0,1.19,Drama,Anamaria Marinca,"4 Months, 3 Weeks and 2 Days",44763,172.0,Romanian,0.59,2007.0,7.9,14000,0.60,246
246,John Carpenter,318.0,47.00,Horror|Thriller,Jamie Lee Curtis,Halloween,157857,1191.0,English,0.30,1978.0,7.9,12000,46.70,247
247,John Carpenter,318.0,47.00,Horror|Thriller,Jamie Lee Curtis,Halloween,157863,1191.0,English,0.30,1978.0,7.9,12000,46.70,248
248,David O. Russell,410.0,93.57,Biography|Drama|Sport,Christian Bale,The Fighter,275869,389.0,English,25.00,2010.0,7.9,36000,68.57,249
249,Michael Mann,209.0,28.97,Biography|Drama|Thriller,Al Pacino,The Insider,133526,521.0,English,68.00,1999.0,7.9,0,-39.03,250

In [24]:
# Write your code to extract top foreign language films from 'IMDb_Top_250' here
Top_Foreign_Lang_Film = IMDb_Top_250[~(IMDb_Top_250['language']=='English')]
Top_Foreign_Lang_Film

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,rank
6,Sergio Leone,181.0,6.10,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780.0,Italian,1.20,1966.0,8.9,20000,4.90,7
14,Fernando Meirelles,214.0,7.56,Crime|Drama,Alice Braga,City of God,533200,749.0,Portuguese,3.30,2002.0,8.7,28000,4.26,15
16,Akira Kurosawa,153.0,0.27,Action|Adventure|Drama,Takashi Shimura,Seven Samurai,229012,596.0,Japanese,2.00,1954.0,8.7,11000,-1.73,17
25,Hayao Miyazaki,246.0,10.05,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Spirited Away,417971,902.0,Japanese,19.00,2001.0,8.6,28000,-8.95,26
42,Majid Majidi,46.0,0.93,Drama|Family,Bahare Seddiqi,Children of Heaven,27882,130.0,Persian,0.18,1997.0,8.5,0,0.75,43
45,Florian Henckel von Donnersmarck,215.0,11.28,Drama|Thriller,Sebastian Koch,The Lives of Others,259379,407.0,German,2.00,2006.0,8.5,39000,9.28,46
46,S.S. Rajamouli,44.0,6.50,Action|Adventure|Drama|Fantasy|War,Tamannaah Bhatia,Baahubali: The Beginning,62756,410.0,Telugu,18.03,2015.0,8.4,21000,-11.53,47
48,Asghar Farhadi,354.0,7.10,Drama|Mystery,Shahab Hosseini,A Separation,151812,264.0,Persian,0.50,2011.0,8.4,48000,6.60,49
51,Jean-Pierre Jeunet,242.0,33.20,Comedy|Romance,Mathieu Kassovitz,Amélie,534262,1314.0,French,77.00,2001.0,8.4,39000,-43.80,52
56,Chan-wook Park,305.0,2.18,Drama|Mystery|Thriller,Min-sik Choi,Oldboy,356181,809.0,Korean,3.00,2003.0,8.4,43000,-0.82,57
57,Hayao Miyazaki,174.0,2.30,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,2400.00,1997.0,8.4,11000,-2397.70,58
59,Wolfgang Petersen,96.0,11.43,Adventure|Drama|Thriller|War,Jürgen Prochnow,Das Boot,168203,426.0,German,14.00,1981.0,8.4,11000,-2.57,60
67,Fritz Lang,260.0,0.03,Drama|Sci-Fi,Brigitte Helm,Metropolis,111841,413.0,German,6.00,1927.0,8.3,12000,-5.97,68
69,Thomas Vinterberg,349.0,0.61,Drama,Thomas Bo Larsen,The Hunt,170155,249.0,Danish,3.80,2012.0,8.3,60000,-3.19,70
73,Oliver Hirschbiegel,192.0,5.50,Biography|Drama|History|War,Thomas Kretschmann,Downfall,248354,564.0,German,13.50,2004.0,8.3,14000,-8.00,74
87,Denis Villeneuve,226.0,6.86,Drama|Mystery|War,Lubna Azabal,Incendies,80429,156.0,French,6.80,2010.0,8.2,37000,0.06,88
95,Juan José Campanella,262.0,20.17,Drama|Mystery|Thriller,Ricardo Darín,The Secret in Their Eyes,131831,231.0,Spanish,2.00,2009.0,8.2,33000,18.17,96
103,Guillermo del Toro,406.0,37.62,Drama|Fantasy|War,Ivana Baquero,Pan's Labyrinth,467234,1083.0,Spanish,13.50,2006.0,8.2,27000,24.12,104
106,Hayao Miyazaki,212.0,4.71,Adventure|Animation|Family|Fantasy,Christian Bale,Howl's Moving Castle,214091,330.0,Japanese,24.00,2004.0,8.2,13000,-19.29,107
108,José Padilha,142.0,0.01,Action|Crime|Drama|Thriller,Wagner Moura,Elite Squad,81644,107.0,Portuguese,4.00,2007.0,8.1,11000,-3.99,109
111,Katsuhiro Ôtomo,150.0,0.44,Action|Animation|Sci-Fi,Mitsuo Iwata,Akira,106160,430.0,Japanese,1100.00,1988.0,8.1,0,-1099.56,112
122,Je-kyu Kang,86.0,1.11,Action|Drama|War,Min-sik Choi,Tae Guk Gi: The Brotherhood of War,31943,224.0,Korean,12.80,2004.0,8.1,0,-11.69,123
123,Thomas Vinterberg,98.0,1.65,Drama,Ulrich Thomsen,The Celebration,65951,258.0,Danish,1.30,1998.0,8.1,5000,0.35,124
137,Alejandro Amenábar,157.0,2.09,Biography|Drama|Romance,Belén Rueda,The Sea Inside,64556,140.0,Spanish,10.00,2004.0,8.1,0,-7.91,138
147,Alejandro G. Iñárritu,157.0,5.38,Drama|Thriller,Adriana Barraza,Amores Perros,173551,361.0,Spanish,2.00,2000.0,8.1,11000,3.38,148
155,Ari Folman,231.0,2.28,Animation|Biography|Documentary|Drama|History|War,Ari Folman,Waltz with Bashir,46107,156.0,Hebrew,1.50,2008.0,8.0,0,0.78,156
162,Vincent Paronnaud,242.0,4.44,Animation|Biography|Drama|War,Catherine Deneuve,Persepolis,70194,158.0,French,7.30,2007.0,8.0,14000,-2.86,163
165,Karan Johar,210.0,4.02,Adventure|Drama|Thriller,Shah Rukh Khan,My Name Is Khan,69759,235.0,Hindi,12.00,2010.0,8.0,27000,-7.98,166
181,Sergio Leone,122.0,3.50,Action|Drama|Western,Clint Eastwood,A Fistful of Dollars,147566,235.0,Italian,0.20,1964.0,8.0,0,3.30,182
199,Walter Salles,71.0,5.60,Drama,Fernanda Montenegro,Central Station,28951,257.0,Portuguese,2.90,1998.0,8.0,0,2.70,200
205,Michael Haneke,447.0,0.23,Drama|Romance,Isabelle Huppert,Amour,70382,190.0,French,8.90,2012.0,7.9,33000,-8.67,206
207,Clint Eastwood,251.0,13.75,Drama|History|War,Yuki Matsuzaki,Letters from Iwo Jima,132149,316.0,Japanese,19.00,2006.0,7.9,5000,-5.25,208
210,Ang Lee,287.0,128.07,Action|Drama|Romance,Chen Chang,"Crouching Tiger, Hidden Dragon",217740,1641.0,Mandarin,15.00,2000.0,7.9,0,113.07,211
226,Yash Chopra,29.0,2.92,Drama|Musical|Romance,Shah Rukh Khan,Veer-Zaara,34449,119.0,Hindi,7.00,2004.0,7.9,2000,-4.08,227
237,Fabián Bielinsky,94.0,1.22,Crime|Drama|Thriller,Ricardo Darín,Nine Queens,38215,125.0,Spanish,1.50,2000.0,7.9,0,-0.28,238
240,Christophe Barratier,112.0,3.63,Drama|Music,Jean-Baptiste Maunier,The Chorus,44151,110.0,French,5.50,2004.0,7.9,0,-1.87,241
241,Yimou Zhang,283.0,0.08,Action|Adventure|History,Jet Li,Hero,149414,841.0,Mandarin,31.00,2002.0,7.9,0,-30.92,242
245,Cristian Mungiu,233.0,1.19,Drama,Anamaria Marinca,"4 Months, 3 Weeks and 2 Days",44763,172.0,Romanian,0.59,2007.0,7.9,14000,0.60,246

**Checkpoint 3:** Can you spot `Veer-Zaara` in the dataframe?

In [25]:
# Verification for checkpoint 3
Top_Foreign_Lang_Film[Top_Foreign_Lang_Film.movie_title.str.contains('Veer-Zaara')]

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,rank
226,Yash Chopra,29.0,2.92,Drama|Musical|Romance,Shah Rukh Khan,Veer-Zaara,34449,119.0,Hindi,7.0,2004.0,7.9,2000,-4.08,227

- ### Subtask 3.5: Find the best directors

    1. Group the dataframe using the `director_name` column.
    2. Find out the top 10 directors for whom the mean of `imdb_score` is the highest and store them in a new dataframe `top10director`.

In [26]:
# Write your code for extracting the top 10 directors here
movies_by_director_name = movies.groupby(['director_name'])
top10director = pd.DataFrame(round(movies_by_director_name['imdb_score'].mean(),1)).sort_values(by=['imdb_score'],ascending=False).head(10)
top10director = top10director.reset_index(drop=False).set_index(np.arange(1,11))
top10director

        director_name  imdb_score
1           Tony Kaye         8.6
2     Charles Chaplin         8.6
3        Majid Majidi         8.5
4    Alfred Hitchcock         8.5
5     Damien Chazelle         8.5
6          Ron Fricke         8.5
7      Asghar Farhadi         8.4
8      S.S. Rajamouli         8.4
9        Sergio Leone         8.4
10  Christopher Nolan         8.4

**Checkpoint 4:** No surprises that `Damien Chazelle` (director of Whiplash and La La Land) is in this list.

In [27]:
# Verification for checkpoint 4
top10director[top10director.director_name=='Damien Chazelle']

     director_name  imdb_score
5  Damien Chazelle         8.5

-  ### Subtask 3.6: Find popular genres

You might have noticed the `genres` column in the dataframe with all the genres of the movies seperated by a pipe (`|`). Out of all the movie genres, the first two are most significant for any film.

1. Extract the first two genres from the `genres` column and store them in two new columns: `genre_1` and `genre_2`. Some of the movies might have only one genre. In such cases, extract the single genre into both the columns, i.e. for such movies the `genre_2` will be the same as `genre_1`.
2. Group the dataframe using `genre_1` as the primary column and `genre_2` as the secondary column.
3. Find out the 5 most popular combo of genres by finding the mean of the gross values using the `gross` column and store them in a new dataframe named `PopGenre`.

In [28]:
# Write your code for extracting the first two genres of each movie here
genres_dataframe = movies["genres"].str.split("|", n = 2, expand = True)
movies[['genre_1','genre_2']] = genres_dataframe[[0,1]]
movies['genre_2'] = np.where(movies['genre_2'].isnull(),movies['genre_1'],movies['genre_2'])
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
0,James Cameron,723.0,760.51,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.00,2009.0,7.9,33000,523.51,Action,Adventure
29,Colin Trevorrow,644.0,652.18,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.00,2015.0,7.0,150000,502.18,Action,Adventure
26,James Cameron,315.0,658.67,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.00,1997.0,7.7,26000,458.67,Drama,Romance
3024,George Lucas,282.0,460.94,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.00,1977.0,8.7,33000,449.94,Action,Adventure
3080,Steven Spielberg,215.0,434.95,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.50,1982.0,7.9,34000,424.45,Family,Sci-Fi
794,Joss Whedon,703.0,623.28,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.00,2012.0,8.1,123000,403.28,Action,Adventure
509,Roger Allers,186.0,422.78,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.00,1994.0,8.5,17000,377.78,Adventure,Animation
240,George Lucas,320.0,474.54,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115.00,1999.0,6.5,13000,359.54,Action,Adventure
66,Christopher Nolan,645.0,533.32,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.00,2008.0,9.0,37000,348.32,Action,Crime
439,Gary Ross,673.0,408.00,Adventure|Drama|Sci-Fi|Thriller,Jennifer Lawrence,The Hunger Games,701607,1959.0,English,78.00,2012.0,7.3,140000,330.00,Adventure,Drama
812,Tim Miller,579.0,363.02,Action|Adventure|Comedy|Romance|Sci-Fi,Ryan Reynolds,Deadpool,479047,1058.0,English,58.00,2016.0,8.1,117000,305.02,Action,Adventure
186,Francis Lawrence,502.0,424.65,Adventure|Sci-Fi|Thriller,Jennifer Lawrence,The Hunger Games: Catching Fire,498397,706.0,English,130.00,2013.0,7.6,82000,294.65,Adventure,Sci-Fi
697,Steven Spielberg,308.0,356.78,Adventure|Sci-Fi|Thriller,Wayne Knight,Jurassic Park,613473,895.0,English,63.00,1993.0,8.1,19000,293.78,Adventure,Sci-Fi
521,Pierre Coffin,306.0,368.05,Animation|Comedy|Family|Sci-Fi,Steve Carell,Despicable Me 2,286877,284.0,English,76.00,2013.0,7.5,56000,292.05,Animation,Comedy
814,Clint Eastwood,490.0,350.12,Action|Biography|Drama|History|Thriller|War,Bradley Cooper,American Sniper,325264,916.0,English,58.80,2014.0,7.3,112000,291.32,Action,Biography
338,Andrew Stanton,301.0,380.84,Adventure|Animation|Comedy|Family,Alexander Gould,Finding Nemo,692482,866.0,English,94.00,2003.0,8.2,11000,286.84,Adventure,Animation
582,Andrew Adamson,205.0,436.47,Adventure|Animation|Comedy|Family|Fantasy|Romance,Rupert Everett,Shrek 2,314630,483.0,English,150.00,2004.0,7.2,0,286.47,Adventure,Animation
339,Peter Jackson,328.0,377.02,Action|Adventure|Drama|Fantasy,Orlando Bloom,The Lord of the Rings: The Return of the King,1215718,3189.0,English,94.00,2003.0,8.9,16000,283.02,Action,Adventure
1536,Richard Marquand,197.0,309.13,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode VI - Return of the Jedi,681857,647.0,English,32.50,1983.0,8.4,14000,276.63,Action,Adventure
836,Robert Zemeckis,149.0,329.69,Comedy|Drama,Tom Hanks,Forrest Gump,1251222,1398.0,English,55.00,1994.0,8.8,59000,274.69,Comedy,Drama
2051,Irvin Kershner,223.0,290.16,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode V - The Empire Strikes Back,837759,900.0,English,18.00,1980.0,8.8,17000,272.16,Action,Adventure
2601,Chris Columbus,102.0,285.76,Comedy|Family,Macaulay Culkin,Home Alone,311075,305.0,English,18.00,1990.0,7.5,20000,267.76,Comedy,Family
236,George Lucas,359.0,380.26,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode III - Revenge of the Sith,520104,3286.0,English,113.00,2005.0,7.6,10000,267.26,Action,Adventure
161,Sam Raimi,291.0,403.71,Action|Adventure|Fantasy|Romance,J.K. Simmons,Spider-Man,544665,2012.0,English,139.00,2002.0,7.3,5000,264.71,Action,Adventure
563,Kyle Balda,308.0,336.03,Action|Animation|Comedy|Family|Sci-Fi,Steve Carell,Minions,142403,275.0,English,74.00,2015.0,6.4,70000,262.03,Action,Animation
1181,M. Night Shyamalan,234.0,293.50,Drama|Mystery|Thriller,Bruce Willis,The Sixth Sense,704766,2073.0,English,40.00,1999.0,8.1,14000,253.50,Drama,Mystery
2917,Steven Spielberg,385.0,260.00,Adventure|Drama|Thriller,Roy Scheider,Jaws,412454,962.0,English,8.00,1975.0,8.0,21000,252.00,Adventure,Drama
125,Chris Buck,406.0,400.74,Adventure|Animation|Comedy|Family|Fantasy|Musical,Josh Gad,Frozen,421658,904.0,English,150.00,2013.0,7.6,58000,250.74,Adventure,Animation
519,Yarrow Cheney,165.0,323.51,Animation|Comedy|Family,Steve Coogan,The Secret Life of Pets,24407,155.0,English,75.00,2016.0,6.8,36000,248.51,Animation,Comedy
926,Chris Weitz,299.0,296.62,Adventure|Drama|Fantasy|Romance,Robert Pattinson,The Twilight Saga: New Moon,220758,919.0,English,50.00,2009.0,4.6,13000,246.62,Adventure,Drama
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,Duncan Jones,275.0,46.98,Action|Adventure|Fantasy,Dominic Cooper,Warcraft,111609,781.0,English,160.00,2016.0,7.3,89000,-113.02,Action,Adventure
3879,Joe Wright,256.0,34.96,Adventure|Family|Fantasy,Hugh Jackman,Pan,39975,186.0,English,150.00,2015.0,5.8,24000,-115.04,Adventure,Family
145,Joe Wright,256.0,34.96,Adventure|Family|Fantasy,Hugh Jackman,Pan,39956,186.0,English,150.00,2015.0,5.8,24000,-115.04,Adventure,Family
113,Oliver Stone,248.0,34.29,Action|Adventure|Biography|Drama|History|Roman...,Anthony Hopkins,Alexander,138863,1390.0,English,155.00,2004.0,5.5,0,-120.71,Action,Adventure
14,Gore Verbinski,450.0,89.29,Action|Adventure|Western,Johnny Depp,The Lone Ranger,181792,711.0,English,215.00,2013.0,6.5,48000,-125.71,Action,Adventure
143,Simon Wells,132.0,21.38,Action|Adventure|Animation|Comedy|Family|Sci-Fi,Elisabeth Harnois,Mars Needs Moms,17590,112.0,English,150.00,2011.0,5.4,0,-128.62,Action,Adventure
62,Lana Wachowski,384.0,47.38,Action|Adventure|Sci-Fi,Channing Tatum,Jupiter Ascending,139593,720.0,English,176.00,2015.0,5.4,44000,-128.62,Action,Adventure
49,Bryan Singer,338.0,65.17,Adventure|Fantasy,Eddie Marsan,Jack the Giant Slayer,106416,205.0,English,195.00,2013.0,6.3,22000,-129.83,Adventure,Fantasy
85,Carl Rinsch,218.0,38.30,Action|Adventure|Drama|Fantasy,Keanu Reeves,47 Ronin,116994,324.0,English,175.00,2013.0,6.3,35000,-136.70,Action,Adventure
2339,Jean-Marie Poiré,8.0,0.15,Comedy|Family|Fantasy|Sci-Fi,Christian Clavier,Les couloirs du temps: Les visiteurs II,7147,16.0,French,140.00,1998.0,6.0,136,-139.85,Comedy,Family
28,Peter Berg,377.0,65.17,Action|Adventure|Sci-Fi|Thriller,Liam Neeson,Battleship,202382,751.0,English,209.00,2012.0,5.9,44000,-143.83,Action,Adventure
1782,Jacques Perrin,100.0,10.76,Documentary,Jacques Perrin,Winged Migration,10369,153.0,English,160.00,2001.0,8.0,1000,-149.24,Documentary,Documentary
3877,R. Balki,12.0,0.20,Comedy|Drama,Vidya Balan,Paa,7295,49.0,Hindi,150.00,2009.0,7.2,504,-149.80,Comedy,Drama
91,Robert Zemeckis,188.0,0.67,Adventure|Animation|Family|Fantasy,Tom Hanks,The Polar Express,120798,444.0,English,165.00,2004.0,6.6,10000,-164.33,Adventure,Animation
3659,Prachya Pinkaew,112.0,11.91,Action|Crime|Drama|Thriller,Jon Foo,The Protector,30210,214.0,Thai,200.00,2005.0,7.1,0,-188.09,Action,Crime
5,Andrew Stanton,462.0,73.06,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263.70,2012.0,6.6,24000,-190.64,Action,Adventure
2740,Tony Jaa,110.0,0.10,Action,Nirut Sirichanya,Ong-bak 2,24570,72.0,Thai,300.00,2008.0,6.2,0,-299.90,Action,Action
1016,Luc Besson,111.0,14.13,Adventure|Biography|Drama|History|War,Paul Brooke,The Messenger: The Story of Joan of Arc,55889,390.0,English,390.00,1999.0,6.4,0,-375.87,Adventure,Biography
3311,Chatrichalerm Yukol,31.0,0.45,Action|Adventure|Drama|History|War,Sarunyu Wongkrachang,The Legend of Suriyothai,1666,47.0,Thai,400.00,2001.0,6.6,124,-399.55,Action,Adventure
1338,John Woo,160.0,0.63,Action|Adventure|Drama|History|War,Takeshi Kaneshiro,Red Cliff,36894,105.0,Mandarin,553.63,2008.0,7.4,0,-553.00,Action,Adventure
3273,Anurag Basu,41.0,1.60,Action|Drama|Romance|Thriller,Bárbara Mori,Kites,9673,106.0,English,600.00,2010.0,6.0,0,-598.40,Action,Drama
3075,Karan Johar,20.0,3.28,Drama,Shah Rukh Khan,Kabhi Alvida Naa Kehna,13998,264.0,Hindi,700.00,2006.0,6.0,659,-696.72,Drama,Drama
3851,Carlos Saura,35.0,1.69,Drama|Musical,Mía Maestro,Tango,2412,40.0,Spanish,700.00,1998.0,7.2,539,-698.31,Drama,Musical
4542,Takao Okawara,107.0,10.04,Action|Adventure|Drama|Sci-Fi|Thriller,Hiroshi Abe,Godzilla 2000,5442,140.0,Japanese,1000.00,1999.0,6.0,339,-989.96,Action,Adventure
3423,Katsuhiro Ôtomo,150.0,0.44,Action|Animation|Sci-Fi,Mitsuo Iwata,Akira,106160,430.0,Japanese,1100.00,1988.0,8.1,0,-1099.56,Action,Animation
2334,Katsuhiro Ôtomo,105.0,0.41,Action|Adventure|Animation|Family|Sci-Fi|Thriller,William Hootkins,Steamboy,13727,79.0,Japanese,2127.52,2004.0,6.9,973,-2127.11,Action,Adventure
2323,Hayao Miyazaki,174.0,2.30,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,2400.00,1997.0,8.4,11000,-2397.70,Adventure,Animation
3005,Lajos Koltai,73.0,0.20,Drama|Romance|War,Marcell Nagy,Fateless,5603,45.0,Hungarian,2500.00,2005.0,7.1,607,-2499.80,Drama,Romance
3859,Chan-wook Park,202.0,0.21,Crime|Drama,Min-sik Choi,Lady Vengeance,53508,131.0,Korean,4200.00,2005.0,7.7,4000,-4199.79,Crime,Drama
2988,Joon-ho Bong,363.0,2.20,Comedy|Drama|Horror|Sci-Fi,Doona Bae,The Host,68883,279.0,Korean,12215.50,2006.0,7.0,7000,-12213.30,Comedy,Drama

In [29]:
# Write your code for grouping the dataframe here
movies_by_segment = movies.groupby(['genre_1','genre_2'])

In [30]:
# Write your code for getting the 5 most popular combo of genres here
PopGenre = pd.DataFrame(round(movies_by_segment['gross'].mean(),2)).sort_values(by='gross',ascending=False).head(5)
PopGenre

                      gross
genre_1   genre_2
Family    Sci-Fi     434.95
Adventure Sci-Fi     228.63
          Family     118.92
          Animation  117.00
Action    Adventure  109.60

**Checkpoint 5:** Well, as it turns out. `Family + Sci-Fi` is the most popular combo of genres out there!

-  ### Subtask 3.7: Find the critic-favorite and audience-favorite actors

    1. Create three new dataframes namely, `Meryl_Streep`, `Leo_Caprio`, and `Brad_Pitt` which contain the movies in which the actors: 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' are the lead actors. Use only the `actor_1_name` column for extraction. Also, make sure that you use the names 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' for the said extraction.
    2. Append the rows of all these dataframes and store them in a new dataframe named `Combined`.
    3. Group the combined dataframe using the `actor_1_name` column.
    4. Find the mean of the `num_critic_for_reviews` and `num_user_for_review` and identify the actors which have the highest mean.

In [31]:
# Write your code for creating three new dataframes here
 # Include all movies in which Meryl_Streep is the lead
Meryl_Streep = movies[movies['actor_1_name']=='Meryl Streep']

In [32]:
# Include all movies in which Leo_Caprio is the lead
Leo_Caprio = movies[movies['actor_1_name']=='Leonardo DiCaprio']

In [33]:
# Include all movies in which Brad_Pitt is the lead
Brad_Pitt = movies[movies['actor_1_name']=='Brad Pitt']

In [34]:
# Write your code for combining the three dataframes here
combined = pd.concat([Meryl_Streep,Leo_Caprio,Brad_Pitt],axis=0)
combined

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
1408,David Frankel,208.0,124.73,Comedy|Drama|Romance,Meryl Streep,The Devil Wears Prada,286178,631.0,English,35.0,2006.0,6.8,0,89.73,Comedy,Drama
1575,Sydney Pollack,66.0,87.10,Biography|Drama|Romance,Meryl Streep,Out of Africa,52339,200.0,English,31.0,1985.0,7.2,0,56.10,Biography,Drama
1204,Nora Ephron,252.0,94.13,Biography|Drama|Romance,Meryl Streep,Julie & Julia,79264,277.0,English,40.0,2009.0,7.0,13000,54.13,Biography,Drama
1618,David Frankel,234.0,63.54,Comedy|Drama|Romance,Meryl Streep,Hope Springs,34258,178.0,English,30.0,2012.0,6.3,0,33.54,Comedy,Drama
410,Nancy Meyers,187.0,112.70,Comedy|Drama|Romance,Meryl Streep,It's Complicated,69860,214.0,English,85.0,2009.0,6.6,0,27.70,Comedy,Drama
2781,Phyllida Lloyd,331.0,29.96,Biography|Drama|History,Meryl Streep,The Iron Lady,82327,350.0,English,13.0,2011.0,6.4,18000,16.96,Biography,Drama
1925,Stephen Daldry,174.0,41.60,Drama|Romance,Meryl Streep,The Hours,102123,660.0,English,25.0,2002.0,7.6,0,16.60,Drama,Romance
3135,Robert Altman,211.0,20.34,Comedy|Drama|Music,Meryl Streep,A Prairie Home Companion,19655,280.0,English,10.0,2006.0,6.8,683,10.34,Comedy,Drama
1106,Curtis Hanson,42.0,46.82,Action|Adventure|Crime|Thriller,Meryl Streep,The River Wild,32544,69.0,English,45.0,1994.0,6.3,0,1.82,Action,Adventure
1674,Carl Franklin,64.0,23.21,Drama,Meryl Streep,One True Thing,9283,112.0,English,30.0,1998.0,7.0,592,-6.79,Drama,Drama
1483,Robert Redford,227.0,15.00,Drama|Thriller|War,Meryl Streep,Lions for Lambs,41170,298.0,English,35.0,2007.0,6.2,0,-20.00,Drama,Thriller
26,James Cameron,315.0,658.67,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.67,Drama,Romance
97,Christopher Nolan,642.0,292.57,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200,2803.0,English,160.0,2010.0,8.8,175000,132.57,Action,Adventure
911,Steven Spielberg,194.0,164.44,Biography|Crime|Drama,Leonardo DiCaprio,Catch Me If You Can,525801,667.0,English,52.0,2002.0,8.0,15000,112.44,Biography,Crime
296,Quentin Tarantino,765.0,162.80,Drama|Western,Leonardo DiCaprio,Django Unchained,955174,1193.0,English,100.0,2012.0,8.5,199000,62.80,Drama,Western
179,Alejandro G. Iñárritu,556.0,183.64,Adventure|Drama|Thriller|Western,Leonardo DiCaprio,The Revenant,406020,1188.0,English,135.0,2015.0,8.1,190000,48.64,Adventure,Drama
452,Martin Scorsese,490.0,127.97,Mystery|Thriller,Leonardo DiCaprio,Shutter Island,786092,964.0,English,80.0,2010.0,8.1,53000,47.97,Mystery,Thriller
361,Martin Scorsese,352.0,132.37,Crime|Drama|Thriller,Leonardo DiCaprio,The Departed,873649,2054.0,English,90.0,2006.0,8.5,29000,42.37,Crime,Drama
3476,Baz Luhrmann,490.0,144.81,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362933,753.0,English,105.0,2013.0,7.3,115000,39.81,Drama,Romance
50,Baz Luhrmann,490.0,144.81,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362912,753.0,English,105.0,2013.0,7.3,115000,39.81,Drama,Romance
2757,Baz Luhrmann,106.0,46.34,Drama|Romance,Leonardo DiCaprio,Romeo + Juliet,167750,506.0,English,14.5,1996.0,6.8,10000,31.84,Drama,Romance
1422,Randall Wallace,83.0,56.88,Action|Adventure,Leonardo DiCaprio,The Man in the Iron Mask,125219,244.0,English,35.0,1998.0,6.4,0,21.88,Action,Adventure
308,Martin Scorsese,606.0,116.87,Biography|Comedy|Crime|Drama,Leonardo DiCaprio,The Wolf of Wall Street,780588,1138.0,English,100.0,2013.0,8.2,138000,16.87,Biography,Comedy
1453,Clint Eastwood,392.0,37.30,Biography|Crime|Drama,Leonardo DiCaprio,J. Edgar,102728,279.0,English,35.0,2011.0,6.6,16000,2.30,Biography,Crime
257,Martin Scorsese,267.0,102.61,Biography|Drama,Leonardo DiCaprio,The Aviator,264318,799.0,English,110.0,2004.0,7.5,0,-7.39,Biography,Drama
990,Danny Boyle,118.0,39.78,Adventure|Drama|Thriller,Leonardo DiCaprio,The Beach,176169,548.0,English,50.0,2000.0,6.6,0,-10.22,Adventure,Drama
2067,Jerry Zaks,45.0,12.78,Drama,Leonardo DiCaprio,Marvin's Room,20163,71.0,English,23.0,1996.0,6.7,1000,-10.22,Drama,Drama
1114,Sam Mendes,323.0,22.88,Drama|Romance,Leonardo DiCaprio,Revolutionary Road,152591,414.0,English,35.0,2008.0,7.3,0,-12.12,Drama,Romance
1560,Sam Raimi,63.0,18.64,Action|Thriller|Western,Leonardo DiCaprio,The Quick and the Dead,69197,216.0,English,32.0,1995.0,6.4,0,-13.36,Action,Thriller
326,Martin Scorsese,233.0,77.68,Crime|Drama,Leonardo DiCaprio,Gangs of New York,314033,1166.0,English,100.0,2002.0,7.5,0,-22.32,Crime,Drama
641,Ridley Scott,238.0,39.38,Action|Drama|Thriller,Leonardo DiCaprio,Body of Lies,174248,263.0,English,70.0,2008.0,7.1,0,-30.62,Action,Drama
307,Edward Zwick,166.0,57.37,Adventure|Drama|Thriller,Leonardo DiCaprio,Blood Diamond,400292,657.0,English,100.0,2006.0,8.0,14000,-42.63,Adventure,Drama
400,Steven Soderbergh,186.0,183.41,Crime|Thriller,Brad Pitt,Ocean's Eleven,402645,845.0,English,85.0,2001.0,7.8,0,98.41,Crime,Thriller
255,Doug Liman,233.0,186.34,Action|Comedy|Crime|Romance|Thriller,Brad Pitt,Mr. & Mrs. Smith,348861,798.0,English,120.0,2005.0,6.5,0,66.34,Action,Comedy
940,Neil Jordan,120.0,105.26,Drama|Fantasy|Horror,Brad Pitt,Interview with the Vampire: The Vampire Chroni...,239752,406.0,English,60.0,1994.0,7.6,11000,45.26,Drama,Fantasy
470,David Ayer,406.0,85.71,Action|Drama|War,Brad Pitt,Fury,303185,701.0,English,68.0,2014.0,7.6,82000,17.71,Action,Drama
254,Steven Soderbergh,198.0,125.53,Crime|Thriller,Brad Pitt,Ocean's Twelve,284852,627.0,English,110.0,2004.0,6.4,0,15.53,Crime,Thriller
2204,Alejandro G. Iñárritu,285.0,34.30,Drama,Brad Pitt,Babel,243799,908.0,English,25.0,2006.0,7.5,0,9.30,Drama,Drama
2682,Andrew Dominik,414.0,14.94,Crime|Thriller,Brad Pitt,Killing Them Softly,111625,369.0,English,15.0,2012.0,6.2,20000,-0.06,Crime,Thriller
2898,Tony Scott,122.0,12.28,Action|Crime|Drama|Romance|Thriller,Brad Pitt,True Romance,163492,460.0,English,13.0,1993.0,8.0,15000,-0.72,Action,Crime
2333,Angelina Jolie Pitt,131.0,0.53,Drama|Romance,Brad Pitt,By the Sea,7976,61.0,English,10.0,2015.0,5.3,0,-9.47,Drama,Romance
1490,Terrence Malick,584.0,13.30,Drama|Fantasy,Brad Pitt,The Tree of Life,136367,975.0,English,32.0,2011.0,6.7,39000,-18.70,Drama,Fantasy
101,David Fincher,362.0,127.49,Drama|Fantasy|Romance,Brad Pitt,The Curious Case of Benjamin Button,459346,822.0,English,150.0,2008.0,7.8,23000,-22.51,Drama,Fantasy
683,David Fincher,315.0,37.02,Drama,Brad Pitt,Fight Club,1347461,2968.0,English,63.0,1999.0,8.8,48000,-25.98,Drama,Drama
1722,Andrew Dominik,273.0,3.90,Biography|Crime|Drama|History|Western,Brad Pitt,The Assassination of Jesse James by the Coward...,136104,415.0,English,30.0,2007.0,7.5,0,-26.10,Biography,Crime
611,Jean-Jacques Annaud,76.0,37.90,Adventure|Biography|Drama|History|War,Brad Pitt,Seven Years in Tibet,96385,119.0,English,70.0,1997.0,7.0,0,-32.10,Adventure,Biography
792,Patrick Gilmore,98.0,26.29,Adventure|Animation|Comedy|Drama|Family|Fantas...,Brad Pitt,Sinbad: Legend of the Seven Seas,36144,91.0,English,60.0,2003.0,6.7,880,-33.71,Adventure,Animation
147,Wolfgang Petersen,220.0,133.23,Adventure,Brad Pitt,Troy,381672,1694.0,English,175.0,2004.0,7.2,0,-41.77,Adventure,Adventure
382,Tony Scott,142.0,0.03,Action|Crime|Thriller,Brad Pitt,Spy Game,121259,361.0,English,92.0,2001.0,7.0,0,-91.97,Action,Crime

In [35]:
# Write your code for grouping the combined dataframe here
movies_by_actor_1 = combined.groupby('actor_1_name')

In [36]:
# Write the code for finding the mean of critic reviews and audience reviews here
pd.concat([movies_by_actor_1.num_critic_for_reviews.mean().sort_values(ascending=False),movies_by_actor_1.num_user_for_reviews.mean().sort_values(ascending=False)],axis=1)

                   num_critic_for_reviews  num_user_for_reviews
actor_1_name
Leonardo DiCaprio              330.190476            914.476190
Brad Pitt                      245.000000            742.352941
Meryl Streep                   181.454545            297.181818

**Checkpoint 6:** `Leonardo` has aced both the lists!