In [6]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
# Set pretty printing format for floats
pd.set_option('float_format', '{:.2f}'.format)
# To view all columns
pd.set_option('display.max_columns', 999)
import datetime
from datetime import date

import matplotlib.pyplot as plt

In [5]:
# print sum of primes till n
import math
n=int(input())
print(sum(num for num in range(2,n+1)if all(num%i!=0 for i in range(2,int(math.sqrt(num))+1))))
for num in range(2,n+1):
    if all(num%i!=0 for i in range(2,int(math.sqrt(num))+1)):
        print(num)

10
17
2
3
5
7

In [1]:
# local minima

import numpy as np
input_list = [2,1,3,4,1,5,6,1,7]
#write your code here
minimas=(np.diff(np.sign(np.diff(input_list))) > 0).nonzero()[0] + 1
minimas=[int(x) for x in minimas] #do not change this code, the output should be an integer list for evaluation purposes
print(minimas)

[1, 4, 7]

In [ ]:
# find the longest consecutive sub-string in alphabetical order in a given string. 
# Note that the order determination is case insensitive, i.e. 
# the string "Ab" is considered to be in alphabetical order. 
# You can assume that the input will not have string where the number of possible consecutive sub-strings in alphabetical order is 0.
# i.e. the input will not have a string like "zxec".
string=input()
prevChar = ""
curr_longest = ""
longest = ""
orig = string
for char,origchar in zip(string.lower(),orig):
    if (prevChar<=char):
        curr_longest += origchar
        if len(curr_longest) > len(longest):
            longest= curr_longest
    else:
        curr_longest = origchar
    prevChar = char
print( longest )

In [53]:
n=int(input())
for i in range(n):
    print('#'*(n-i-1) + '*'*(2*i+1) + '#'*(n-i-1))

4
###*###
##***##
#*****#
*******

In [55]:
rows=int(input())
for i in reversed(range(rows)):
    print('#'*(rows-i-1) + '*'*(2*i+1) + '#'*(rows-i-1))

3
*****
#***#
##*##

In [69]:
# if a palindrome can be created
string=input()
from collections import Counter 
res = Counter(string) 
print(res)
count=0
for key in res:
    if (res[key]%2!=0) & (count==1):
        count=2
        break
    if (res[key]%2!=0) & (count==0):
        count=1
if(count>1):
    print('No')
else:
    print('Yes')

aabbc
Counter({'a': 2, 'b': 2, 'c': 1})
Yes

In [87]:
df = pd.read_csv('test.csv')
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.50,0,0,330911,7.83,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00,1,0,363272,7.00,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.00,0,0,240276,9.69,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.00,0,0,315154,8.66,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00,1,1,3101298,12.29,NaN,S

In [73]:
to_omit = ['PassengerId', 'Pclass', 'Name', 'Sex','Embarked']
cols = df.columns[~df.columns.isin(to_omit)].sort_values()
df[cols].head(5)

    Age Cabin  Fare  Parch  SibSp   Ticket
0 34.50   NaN  7.83      0      0   330911
1 47.00   NaN  7.00      0      1   363272
2 62.00   NaN  9.69      0      0   240276
3 27.00   NaN  8.66      0      0   315154
4 22.00   NaN 12.29      1      1  3101298

In [88]:
# Given a dataframe, you have to group it by given column name(list of column names). After that you should print data of the group with a specified column value(values). 
# The input will contain two lines. First line will have a list of columns and second will have a list of values.
# The output should have the first five rows of the corresponding group.(there can be less than five rows in a group too)

cols = ['Name','PassengerId']
values = ['Abbott, Master. Eugene Joseph',1284]
print(df.groupby(cols).get_group(tuple(values)).head())

     PassengerId  Pclass                           Name   Sex   Age  SibSp  \
392         1284       3  Abbott, Master. Eugene Joseph  male 13.00      0

     Parch     Ticket  Fare Cabin Embarked
392      2  C.A. 2673 20.25   NaN        S

In [91]:
for word,value in zip(cols,values):
    if isinstance(value, str):
        exp = word+'=='+'\''+str(value)+'\''
    else:
        exp = word+'=='+str(value)
    df.query(exp,inplace=True)
print(df.head())

     PassengerId  Pclass                           Name   Sex   Age  SibSp  \
392         1284       3  Abbott, Master. Eugene Joseph  male 13.00      0

     Parch     Ticket  Fare Cabin Embarked
392      2  C.A. 2673 20.25   NaN        S

In [73]:
arr1 = np.array([[4,3,2,1]])
arr2 = np.array([[8,7,6,5]])
arr3 = np.concatenate((arr1,arr2),axis=1)
print(arr3)
arr4 = np.array([[15,16,17,18,12,13,14,11]])
arr6 = np.array([[9,8,7,6,5,4,3,20]])
arr5 = np.concatenate((arr3,arr4,arr6),axis=0)
print(arr5)

[[4 3 2 1 8 7 6 5]]
[[ 4  3  2  1  8  7  6  5]
 [15 16 17 18 12 13 14 11]
 [ 9  8  7  6  5  4  3 20]]

In [81]:
df = pd.DataFrame(arr5)
df[len(df.columns)] = 0
df

    0   1   2   3   4   5   6   7  8
0   4   3   2   1   8   7   6   5  0
1  15  16  17  18  12  13  14  11  0
2   9   8   7   6   5   4   3  20  0

In [82]:
df.iloc[:,-1][df.iloc[:,len(df.columns)-2] > 10] = 1
df

C:\Users\H253015\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

    0   1   2   3   4   5   6   7  8
0   4   3   2   1   8   7   6   5  0
1  15  16  17  18  12  13  14  11  1
2   9   8   7   6   5   4   3  20  1

In [77]:
# df[df.iloc[:,-1] > 10].iloc[:,-1] = 1
# df.iloc[df[:,-1] > 10, -1] = 0
# df.iloc[:,-1][df.iloc[:,-1] > 10] = 0
if df.iloc[-1,-1] > 10:
    df[len(df.columns)] = 0
    df.iloc[:,-1][df.iloc[:,len(df.columns)-2] > 10] = 1
else:
    df[len(df.columns)] = 0
df

C:\Users\H253015\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

    0   1   2   3   4   5   6   7  8
0   4   3   2   1   8   7   6   5  0
1  15  16  17  18  12  13  14  11  1
2   9   8   7   6   5   4   3  20  1

In [59]:
df

    0   1   2   3   4   5   6  7
0   4   3   2   1   8   7   6  5
1  15  16  17  18  12  13  14  0
2   9   8   7   6   5   4   3  2

In [22]:
df.to_csv('C:/Users/H253015/Desktop/my_csv.csv', mode='a', header=False,index=False)

11

In [23]:
df = pd.read_csv('C:/Users/H253015/Desktop/saffronseahorse-1-site-5_structured_data.csv')

In [21]:
df.head()

,TalkmanLineCnt,TalkmanPickCnt,TalkmanCheckdigitGroupCnt,TalkmanWrongCnt,TalkmanCorrectCnt,TalkmanScanCnt,TalkmanCheckdigitRespCnt,TalkmanItemdigitRespCnt,TalkmanLocationCnt,TalkmanOthersCnt,OprReadyCnt,OprLocationCnt,OprPickDigitsCnt,OprCheckDigitsCnt,OprScanCnt,OprSayagainCnt,OprPrevCnt,OprBackCnt,OprYesCnt,OprNoCnt,OprHelpCnt,OprTalkManCnt,OprOthersCnt,CumOprDialogCnt,CumTalManDialogCnt,ElapsedTimeBetweenDialogs,CumTimeElapsed,Result
0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,27,27,0
2,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,1,0,0,0,0,0,0,0,1,2,1,28,0
3,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,1,0,0,0,0,0,0,0,1,3,10,38,0
4,0,0,0,0,0,0,0,0,0,3,0,0,0,1,0,1,0,0,0,0,0,0,0,2,3,1,39,0

In [24]:
(df == 0).all()

TalkmanLineCnt               False
TalkmanPickCnt               False
TalkmanCheckdigitGroupCnt     True
TalkmanWrongCnt               True
TalkmanCorrectCnt            False
TalkmanScanCnt               False
TalkmanCheckdigitRespCnt     False
TalkmanItemdigitRespCnt      False
TalkmanLocationCnt            True
TalkmanOthersCnt             False
OprReadyCnt                  False
OprLocationCnt               False
OprPickDigitsCnt             False
OprCheckDigitsCnt            False
OprScanCnt                   False
OprSayagainCnt               False
OprPrevCnt                    True
OprBackCnt                   False
OprYesCnt                    False
OprNoCnt                     False
OprHelpCnt                   False
OprTalkManCnt                False
OprOthersCnt                 False
CumOprDialogCnt              False
CumTalManDialogCnt           False
ElapsedTimeBetweenDialogs    False
CumTimeElapsed               False
Result                       False
dtype: bool

In [9]:
df[df.OprNoCnt != 0]

,TalkmanLineCnt,TalkmanPickCnt,TalkmanCheckdigitGroupCnt,TalkmanWrongCnt,TalkmanCorrectCnt,TalkmanScanCnt,TalkmanCheckdigitRespCnt,TalkmanItemdigitRespCnt,TalkmanLocationCnt,TalkmanOthersCnt,OprReadyCnt,OprLocationCnt,OprPickDigitsCnt,OprCheckDigitsCnt,OprScanCnt,OprSayagainCnt,OprPrevCnt,OprBackCnt,OprYesCnt,OprNoCnt,OprHelpCnt,OprTalkManCnt,OprOthersCnt,CumOprDialogCnt,CumTalManDialogCnt,ElapsedTimeBetweenDialogs,CumTimeElapsed
1,0,0,0,0,0,2,0,0,2,0,0,0,2,0,0,0,0,0,0,1,1,1,5,5,0,22,0
1,0,0,0,0,0,2,0,0,3,0,0,0,2,0,0,0,0,0,0,1,1,1,5,6,0,22,0
1,0,0,0,0,0,2,0,0,3,0,0,0,2,0,0,0,0,0,0,1,1,2,6,6,4,26,0
1,0,0,0,1,0,2,0,0,3,0,0,0,2,0,0,0,0,0,0,1,1,2,6,7,1,27,0
1,0,0,0,1,0,2,0,0,3,0,0,0,3,0,0,0,0,0,0,1,1,2,7,7,1,28,0
1,0,0,0,1,0,2,0,0,4,0,0,0,3,0,0,0,0,0,0,1,1,2,7,8,2,30,0
1,0,0,0,1,0,2,0,0,4,0,0,0,4,0,0,0,0,0,0,1,1,2,8,8,2,32,0
1,0,0,0,1,1,2,0,0,4,0,0,0,4,0,0,0,0,0,0,1,1,2,8,9,2,34,0
1,0,0,0,1,1,2,0,0,5,0,0,0,4,0,0,0,0,0,0,1,1,2,8,10,2,36,0
1,0,0,0,1,1,2,0,0,5,0,0,0,4,0,0,0,0,0,0,1,1,3,9,10,0,36,0
1,0,0,0,1,1,2,0,0,5,0,0,0,4,0,0,0,0,0,0,1,1,4,10,10,1,37,0
1,0,0,0,1,1,2,0,0,5,0,0,0,5,0,0,0,0,0,0,1,1,4,11,10,0,37,0
1,0,0,0,2,1,2,0,0,5,0,0,0,5,0,0,0,0,0,0,1,1,4,11,11,3,40,0
1,0,0,0,2,1,2,0,0,5,0,0,0,6,0,0,0,0,0,0,1,1,4,12,11,1,41,0
1,0,0,0,2,1,2,0,0,6,0,0,0,6,0,0,0,0,0,0,1,1,4,12,12,2,43,0
1,0,0,0,2,1,2,0,0,6,0,0,0,7,0,0,0,0,0,0,1,1,4,13,12,1,44,0
1,0,0,0,2,1,2,0,0,7,0,0,0,7,0,0,0,0,0,0,1,1,4,13,13,3,47,0
1,0,0,0,2,1,2,0,0,7,0,0,0,8,0,0,0,0,0,0,1,1,4,14,13,1,48,0
1,0,0,0,2,1,2,0,0,8,0,0,0,8,0,0,0,0,0,0,1,1,4,14,14,1,49,0
1,0,0,0,2,1,2,0,0,9,0,0,0,8,0,0,0,0,0,0,1,1,4,14,15,3,52,0
1,0,0,0,2,1,2,0,0,9,0,0,0,9,0,0,0,0,0,0,1,1,4,15,15,8,60,0
1,0,0,0,2,1,2,0,0,9,0,0,0,9,0,1,0,0,0,0,1,1,4,16,15,15,75,1
1,0,0,0,2,1,2,0,0,10,0,0,0,9,0,1,0,0,0,0,1,1,4,16,16,4,79,1
1,0,0,0,2,1,2,0,0,10,0,0,0,10,0,1,0,0,0,0,1,1,4,17,16,3,82,1
1,0,0,0,2,1,2,0,0,10,0,0,0,11,0,1,0,0,0,0,1,1,4,18,16,34,116,1
1,0,0,0,2,1,2,0,0,10,0,0,0,11,0,1,0,0,0,0,1,1,5,19,16,3,119,1
1,0,0,0,2,1,2,0,0,10,0,0,0,12,0,1,0,0,0,0,1,1,5,20,16,6,125,1
1,0,0,0,3,1,2,0,0,10,0,0,0,12,0,1,0,0,0,0,1,1,5,20,17,3,128,1
1,0,0,0,3,1,2,0,0,10,0,0,0,13,0,1,0,0,0,0,1,1,5,21,17,1,129,1
1,0,0,0,3,1,2,0,0,11,0,0,0,13,0,1,0,0,0,0,1,1,5,21,18,2,131,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6,4,0,0,3,1,2,1,0,20,0,4,17,18,0,0,0,0,0,0,2,2,18,44,33,6,314,1
6,4,0,0,3,1,2,1,0,20,0,4,18,18,0,0,0,0,0,0,2,2,19,45,33,0,314,1
6,4,0,0,4,1,2,1,0,20,0,4,18,18,0,0,0,0,0,0,2,2,19,45,34,2,316,1
6,4,0,0,4,1,2,1,0,20,0,4,19,18,0,0,0,0,0,0,2,2,20,46,34,1,317,1
7,5,0,0,4,1,2,2,0,20,0,4,19,18,0,0,0,0,0,0,2,2,20,46,35,8,325,1
7,5,0,0,4,1,2,2,0,20,0,5,19,18,0,0,0,0,0,0,2,2,20,47,35,6,331,1
7,5,0,0,4,1,2,2,0,21,0,5,19,18,0,0,0,0,0,0,2,2,20,47,36,3,334,1
8,6,0,0,4,1,2,3,0,21,0,5,19,18,0,0,0,0,0,0,2,2,20,47,37,4,338,1
8,6,0,0,4,1,2,3,0,21,0,5,20,18,0,0,0,0,0,0,2,2,21,48,37,16,354,1
8,6,0,0,4,1,2,3,0,21,0,5,21,18,0,0,0,0,0,0,2,2,22,49,37,0,354,1
8,6,0,0,5,1,2,3,0,21,0,5,21,18,0,0,0,0,0,0,2,2,22,49,38,2,356,1
8,6,0,0,5,1,2,3,0,21,0,5,22,18,0,0,0,0,0,0,2,2,23,50,38,2,358,1
8,6,0,0,5,1,2,3,0,22,0,5,22,18,0,0,0,0,0,0,2,2,23,50,39,7,365,1
8,6,0,0,5,1,2,3,0,22,0,6,22,18,0,0,0,0,0,0,2,2,23,51,39,12,377,1
8,6,0,0,5,1,2,3,0,23,0,6,22,18,0,0,0,0,0,0,2,2,23,51,40,3,380,1
8,6,0,0,5,1,2,3,0,24,0,6,22,18,0,0,0,0,0,0,2,2,23,51,41,3,383,1
8,6,0,0,5,1,2,3,0,24,0,6,23,18,0,0,0,0,0,0,2,2,24,52,41,22,405,1
8,6,0,0,5,1,2,3,0,25,0,6,23,18,0,0,0,0,0,0,2,2,24,52,42,3,408,1
8,6,0,0,5,1,2,3,0,25,0,6,24,18,0,0,0,0,0,0,2,2,25,53,42,5,413,1
8,6,0,0,5,1,2,3,0,25,0,6,25,18,0,0,0,0,0,0,2,2,26,54,42,1,414,1
8,6,0,0,5,1,2,3,0,25,0,6,26,18,0,0,0,0,0,0,2,2,27,55,42,0,414,1
8,6,0,0,5,1,2,3,0,25,0,6,27,18,0,0,0,0,0,0,2,2,28,56,42,0,414,1
8,6,0,0,5,1,2,3,0,25,0,6,28,18,0,0,0,0,0,0,2,2,29,57,42,1,415,1
8,7,0,0,5,1,2,3,0,25,0,6,28,18,0,0,0,0,0,0,2,2,29,57,43,3,418,1
8,7,0,0,5,1,2,3,0,25,0,6,29,18,0,0,0,0,0,0,2,2,30,58,43,16,434,1
8,7,0,0,5,1,2,3,0,25,0,6,30,18,0,0,0,0,0,0,2,2,31,59,43,0,434,1
8,7,0,0,5,1,2,3,0,25,0,6,31,18,0,0,0,0,0,0,2,2,32,60,43,1,435,1
8,7,0,0,6,1,2,3,0,25,0,6,31,18,0,0,0,0,0,0,2,2,32,60,44,2,437,1
8,7,0,0,6,1,2,3,0,25,0,6,32,18,0,0,0,0,0,0,2,2,33,61,44,3,440,1
8,7,0,0,6,1,2,3,0,26,0,6,32,18,0,0,0,0,0,0,2,2,33,61,45,5,445,1

In [14]:
voice = 'pick'
s1 = voice.find('pick')
print(s1)

0

In [13]:
import math
math.floor(24/10)

2

In [21]:
import math
import functools

def round(x):
    if(x%10 >=5):
        return math.ceil(x/10)*10
    else:
        return math.floor(x/10)*10

l1 = [2, 18, 10]

list(map(round,l1))

functools.reduce(lambda x, y: x + y, list(map(round,l1)))

30

In [40]:
def alarm_clock(day, vacation):
    if (vacation):
        if day in (1,2,3,4,5):
            return "10:00"
        else:
            return "off"
    else:
        if day in (1,2,3,4,5):
            return "7:00"
        else:
            return "10:00"

In [43]:
print(alarm_clock(3,True))

10:00

In [34]:
print(3 in (1,2,3,4,5))

True

In [ ]:
def F(a,b,c,n):
    if n > b:
        return n-c
    else:
        return F(a + F(a + F(a + F(a + n))))

def large_sum(a, b, c):
    sum=0;
    for x in range(0,b+1):
        sum+=F(a,b,c,x)
    return sum;

pr

In [39]:
import re

k = 'Pick (.*) (.*) (.*)'
dot_star_check = re.compile('(?:\(\.\*\)\\s*)+')
k = re.sub(dot_star_check,'(.*)',k) 
print(k)

Pick (.*)

In [13]:
my_list = [1,2,3,4,5,6,7,8,9] 
n = 3
for i in range((len(my_list) + n - 1) // n ):
    print(my_list[i * n:(i + 1) * n])

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]

In [38]:
input_list = [2017,8,2,2018,1,1] 
dateStart=datetime.date(input_list[0],input_list[1],input_list[2])
dateEnd=datetime.date(input_list[3],input_list[4],input_list[5])
months = ['January','February','March','April','May','June','July','August','September','October','November','December']
sm = dateStart.month
em = dateEnd.month
if(em>=sm):
    print(months[sm-1:em])
else:
    print(months[:em]+months[sm-1:])

['January', 'August', 'September', 'October', 'November', 'December']

In [52]:
list1 = [[1,2,3],[],[4,5],[],[],[6,7,8]]
list2=[]
for lis in list1:
    if((len(lis) != 0)):
        list2.append(lis)
print(list2)

[[1, 2, 3], [4, 5], [6, 7, 8]]

In [5]:
letters = 'cwd'
guess = 'crossword'
yes = True
prevIdx = -1
for cr in letters:
    idx = guess.index(cr)
    if(idx <= prevIdx):
        yes = False
        break
    prevIdx=idx
if(yes):
    print('yes')
else:
    print('no')

yes

In [17]:
name = "vikul aggarwal"
words = name.split(' ')
l = len(words)

for i in range(l):
    words[i] = words[i].capitalize()
    
result = ' '.join(words)

print(result)

Vikul Aggarwal

In [5]:
size=3
width  = size*4-3
string = ''

for i in range(1,size+1):
    for j in range(0,i):
        string += chr(96+size-j)
        if len(string) < width :
            string += '-'
    for k in range(i-1,0,-1):    
        string += chr(97+size-k)
        if len(string) < width :
            string += '-'
    print(string.center(width,'-'))
    string = ''

for i in range(size-1,0,-1):
    string = ''
    for j in range(0,i):
        string += chr(96+size-j)
        if len(string) < width :
            string += '-'
    for k in range(i-1,0,-1):
        string += chr(97+size-k)
        if len(string) < width :
            string += '-'
    print(string.center(width,'-'))

----c----
--c-b-c--
c-b-a-b-c
--c-b-c--
----c----

In [6]:
# print to binary
print("{0:b}".format(int(17)))

10001

In [16]:
# The minion game
S='Australia'
Vowels = ('A' , 'a' , 'E' , 'e' , 'I' , 'i' , 'O' , 'o' , 'U' , 'u')

l = len(S)

sanskar = 0
mahima  = 0

for i in range (l):
    if S[i] in Vowels:
        mahima += l - i
    else:
        sanskar += l - i
        
if sanskar == mahima:
    print ("Draw")
elif sanskar > mahima:
    print ("Sanskar", sanskar)
else:
    print ("Mahima", mahima)

Mahima 24

In [14]:
# Read training data
crime_data = pd.read_csv("https://media-doselect.s3.amazonaws.com/generic/A03q8Gk71oAKYAJvQb47MNaXw/communities_final.csv")
# Assign number of rows to a new variable
number_row = len(crime_data.index)
print(number_row)
# Create a list storing the name of the columns
column_list = crime_data.columns
print(column_list)

1994
Index(['state', 'county', 'community', 'communityname', 'fold', 'population',
       'householdsize', 'racepctblack', 'racePctWhite', 'racePctAsian',
       ...
       'LandArea', 'PopDens', 'PctUsePubTrans', 'PolicCars', 'PolicOperBudg',
       'LemasPctPolicOnPatr', 'LemasGangUnitDeploy', 'LemasPctOfficDrugUn',
       'PolicBudgPerPop', 'ViolentCrimesPerPop'],
      dtype='object', length=128)

In [8]:
data = pd.read_csv("https://media-doselect.s3.amazonaws.com/generic/3rPYLGOBzdbzNbXyKdg1MkWae/training-Dataset.zip", compression='zip')
data.head()

,state,county,community,communityname,fold,population,householdsize,racepctblack,racePctWhite,racePctAsian,racePctHisp,agePct12t21,agePct12t29,agePct16t24,agePct65up,numbUrban,pctUrban,medIncome,pctWWage,pctWFarmSelf,pctWInvInc,pctWSocSec,pctWPubAsst,pctWRetire,medFamInc,perCapInc,whitePerCap,blackPerCap,indianPerCap,AsianPerCap,OtherPerCap,HispPerCap,NumUnderPov,PctPopUnderPov,PctLess9thGrade,PctNotHSGrad,PctBSorMore,PctUnemployed,PctEmploy,PctEmplManu,PctEmplProfServ,PctOccupManu,PctOccupMgmtProf,MalePctDivorce,MalePctNevMarr,FemalePctDiv,TotalPctDiv,PersPerFam,PctFam2Par,PctKids2Par,PctYoungKids2Par,PctTeen2Par,PctWorkMomYoungKids,PctWorkMom,NumIlleg,PctIlleg,NumImmig,PctImmigRecent,PctImmigRec5,PctImmigRec8,PctImmigRec10,PctRecentImmig,PctRecImmig5,PctRecImmig8,PctRecImmig10,PctSpeakEnglOnly,PctNotSpeakEnglWell,PctLargHouseFam,PctLargHouseOccup,PersPerOccupHous,PersPerOwnOccHous,PersPerRentOccHous,PctPersOwnOccup,PctPersDenseHous,PctHousLess3BR,MedNumBR,HousVacant,PctHousOccup,PctHousOwnOcc,PctVacantBoarded,PctVacMore6Mos,MedYrHousBuilt,PctHousNoPhone,PctWOFullPlumb,OwnOccLowQuart,OwnOccMedVal,OwnOccHiQuart,RentLowQ,RentMedian,RentHighQ,MedRent,MedRentPctHousInc,MedOwnCostPctInc,MedOwnCostPctIncNoMtg,NumInShelters,NumStreet,PctForeignBorn,PctBornSameState,PctSameHouse85,PctSameCity85,PctSameState85,LemasSwornFT,LemasSwFTPerPop,LemasSwFTFieldOps,LemasSwFTFieldPerPop,LemasTotalReq,LemasTotReqPerPop,PolicReqPerOffic,PolicPerPop,RacialMatchCommPol,PctPolicWhite,PctPolicBlack,PctPolicHisp,PctPolicAsian,PctPolicMinor,OfficAssgnDrugUnits,NumKindsDrugsSeiz,PolicAveOTWorked,LandArea,PopDens,PctUsePubTrans,PolicCars,PolicOperBudg,LemasPctPolicOnPatr,LemasGangUnitDeploy,LemasPctOfficDrugUn,PolicBudgPerPop,ViolentCrimesPerPop
0,8,nan,nan,Lakewoodcity,1,0.19,0.33,0.02,0.90,0.12,0.17,0.34,0.47,0.29,0.32,0.20,1.00,0.37,0.72,0.34,0.60,0.29,0.15,0.43,0.39,0.40,0.39,0.32,0.27,0.27,0.36,0.41,0.08,0.19,0.10,0.18,0.48,0.27,0.68,0.23,0.41,0.25,0.52,0.68,0.40,0.75,0.75,0.35,0.55,0.59,0.61,0.56,0.74,0.76,0.04,0.14,0.03,0.24,0.27,0.37,0.39,0.07,0.07,0.08,0.08,0.89,0.06,0.14,0.13,0.33,0.39,0.28,0.55,0.09,0.51,0.50,0.21,0.71,0.52,0.05,0.26,0.65,0.14,0.06,0.22,0.19,0.18,0.36,0.35,0.38,0.34,0.38,0.46,0.25,0.04,0.00,0.12,0.42,0.50,0.51,0.64,0.03,0.13,0.96,0.17,0.06,0.18,0.44,0.13,0.94,0.93,0.03,0.07,0.10,0.07,0.02,0.57,0.29,0.12,0.26,0.20,0.06,0.04,0.90,0.50,0.32,0.14,0.20
1,53,nan,nan,Tukwilacity,1,0.00,0.16,0.12,0.74,0.45,0.07,0.26,0.59,0.35,0.27,0.02,1.00,0.31,0.72,0.11,0.45,0.25,0.29,0.39,0.29,0.37,0.38,0.33,0.16,0.30,0.22,0.35,0.01,0.24,0.14,0.24,0.30,0.27,0.73,0.57,0.15,0.42,0.36,1.00,0.63,0.91,1.00,0.29,0.43,0.47,0.60,0.39,0.46,0.53,0.00,0.24,0.01,0.52,0.62,0.64,0.63,0.25,0.27,0.25,0.23,0.84,0.10,0.16,0.10,0.17,0.29,0.17,0.26,0.20,0.82,0.00,0.02,0.79,0.24,0.02,0.25,0.65,0.16,0.00,0.21,0.20,0.21,0.42,0.38,0.40,0.37,0.29,0.32,0.18,0.00,0.00,0.21,0.50,0.34,0.60,0.52,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.02,0.12,0.45,nan,nan,nan,nan,0.00,nan,0.67
2,24,nan,nan,Aberdeentown,1,0.00,0.42,0.49,0.56,0.17,0.04,0.39,0.47,0.28,0.32,0.00,0.00,0.30,0.58,0.19,0.39,0.38,0.40,0.84,0.28,0.27,0.29,0.27,0.07,0.29,0.28,0.39,0.01,0.27,0.27,0.43,0.19,0.36,0.58,0.32,0.29,0.49,0.32,0.63,0.41,0.71,0.70,0.45,0.42,0.44,0.43,0.43,0.71,0.67,0.01,0.46,0.00,0.07,0.06,0.15,0.19,0.02,0.02,0.04,0.05,0.88,0.04,0.20,0.20,0.46,0.52,0.43,0.42,0.15,0.51,0.50,0.01,0.86,0.41,0.29,0.30,0.52,0.47,0.45,0.18,0.17,0.16,0.27,0.29,0.27,0.31,0.48,0.39,0.28,0.00,0.00,0.14,0.49,0.54,0.67,0.56,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.01,0.21,0.02,nan,nan,nan,nan,0.00,nan,0.43
3,34,5.00,81440.00,Willingborotownship,1,0.04,0.77,1.00,0.08,0.12,0.10,0.51,0.50,0.34,0.21,0.06,1.00,0.58,0.89,0.21,0.43,0.36,0.20,0.82,0.51,0.36,0.40,0.39,0.16,0.25,0.36,0.44,0.01,0.10,0.09,0.25,0.31,0.33,0.71,0.36,0.45,0.37,0.39,0.34,0.45,0.49,0.44,0.75,0.65,0.54,0.83,0.65,0.85,0.86,0.03,0.33,0.02,0.11,0.20,0.30,0.31,0.05,0.08,0.11,0.11,0.81,0.08,0.56,0.62,0.85,0.77,1.00,0.94,0.12,0.01,0.50,0.01,0.97,0.96,0.60,0.47,0.52,0.11,0.11,0.24,0.21,0.19,0.75,0.70,0.77,0.89,0.63,0.51,0.47,0.00,0.00,0.19,0.30,0.73,0.64,0.65,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.02,0.39,0.28,nan,nan,nan,nan,0.00,nan,0.12
4,42,95.00,6096.00,Bethlehemtownship,1,0.01,0.55,0.02,0.95,0.09,0.05,0.38,0.38,0.23,0.36,0.02,0.90,0.50,0.72,0.16,0.68,0.44,0.11,0.71,0.46,0.43,0.41,0.28,0.00,0.74,0.51,0.48,0.00,0.06,0.25,0.30,0.33,0.12,0.65,0.67,0.38,0.42,0.46,0.22,0.27,0.20,0.21,0.51,0.91,0.91,0.89,0.85,0.40,0.60,0.00,0.06,0.00,0.03,0.07,0.20,0.27,0.01,0.02,0.04,0.05,0.88,0.05,0.16,0.19,0.59,0.60,0.37,0.89,0.02,0.19,0.50,0.01,0.89,0.87,0.04,0.55,0.73,0.05,0.14,0.31,0.31,0.30,0.40,0.36,0.38,0.38,0.22,0.51,0.21,0.00,0.00,0.11,0.72,0.64,0.61,0.53,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.04,0.09,0.02,nan,nan,nan,nan,0.00,nan,0.03

In [11]:
a = ["apple", "banana", "cherry"]
b = ["Ford"]
print(a[:]+['SalePrice'])

['apple', 'banana', 'cherry', 'SalePrice']

In [ ]:
scores = (9, 9, 18)

def tri_angle(x, y, z):
    if (x*x + y*y < z*z):
        print('Obtuse')
    elif (x*x + y*y == z*z):
        print('Right')
    elif (x*x + y*y > z*z):
        print('Acute')


x, y, z = sorted(scores)

if any([x >= y+z, y >= x+z, z >= x+y]):
    triangle_type = "Invalid"
elif all([x==y, x==z]):
    tri_angle(x,y,z)
    triangle_type = "Equilateral"
elif all([x!=z, z!=y, x!=y]):
    tri_angle(x,y,z)
    triangle_type = "Scalene"
elif any([
        all([x==z, x!=y]),
        all([x==y, x!=z]),
        all([z==y, z!=x]),
    ]):
    tri_angle(x,y,z)
    triangle_type = "Isosceles"
print(triangle_type)

In [ ]:
s = "I Love Python BLABLABLA"
print(max(s.split(' '), key=len))